students/JerryH/Lesson01/break_me.py
=> For Task #1 Practice

students/tri_nguyen/README.rst
=> added a readme file

.gitignore, students/Dustin_L/README.md, students/Dustin_L/lesson01/break_me.py
- Created directories for Dustin_L and lesson01
- Added top-level README
- Updated .gitignore
- Completed lesson01 via break_me.py
=> Dustin_L - Completed Lesson01

students/etwum/lesson02/grid_printer.py
=> Lesson02 - Emmanuel Twum

students/rmart300/README.md, students/rmart300/gridMaker/README.md, students/rmart300/gridMaker/gridMaker.py
let me know if I missed anything!  thanks!
=> completed lesson 2 assignment

students/etwum/lesson02/fizz_buzz.py
=> Lesson 02 - Fizz Buzz Exercise - Emmanuel Twum

students/csdotson/README.rst
Initial PR for Chris Dotson (csdotson). Adding csdotson/ to students directory. Also adding 'README.rst' file.
=> Initial PR - Adding csdotson dir

students/csdotson/lesson01/break_me.py
Submitting break_me.py for Lesson1
=> Add break_me.py for Lesson1

students/itsabhi/README.rst, students/itsabhi/grid.py
Hello,
This is my first assignment and am new to Git. Hope I'm doing this correctly.
=> Lesson2 assignment

students/rmart300/lesson03/README.md, students/rmart300/lesson03/list_lab.py, students/rmart300/slicing/README.md, students/rmart300/slicing/slicing_methods.py
let me know if there are any issues with my interpretation of the needed methods
=> completed lesson 3 assignment

students/Dustin_L/lesson03/slicing.py
Slicing assignment for Lesson03.
=> Dustin_L - Lesson3 - Slicing

students/Dustin_L/lesson03/list_lab.py
List Lab assignment in Lesson03.
=> Dustin_L - Lesson03 - List Lab

students/nDruP/lesson03/strformat_lab.py, students/nDruP/lesson03/strformat_lab.py~
=> Andrew Park Lesson03|strformat_lab.py

students/ZhuojingXie/lesson02/fizzbuzz.py, students/ZhuojingXie/lesson02/printer_exercise.py
I have so many trouble to using loop and using global/local variables. even though I made it eventually.
Should I start from bottom or should I start from Top? What I am trying to say, in this case, is should I focus on how to print out the first line or I should think about what I need to complete  print_grid2(m,n) function at very beginning?
=> print exercise

students/nDruP/lesson03/mailroom.py, students/nDruP/lesson03/strformat_lab.py
=> Andrew Park Mailroom

students/JeroenSweerts/Lesson2/FizzBuzz.py, students/JeroenSweerts/Lesson2/Grid_Printer.py
Please review my code for the Grid Printer Exercise. The code is built up in 3 parts:
1. A function with no arguments
2. A function with 1 argument
3. A function with 2 arguments
The code has been tested and seemed to behave like expected.
Thanks.
Jeroen
=> Grid Printer Excercise, first commit

students/MikeShand/lesson02/print_grid3.py
=> this i a test

students/itsabhi/Lesson2/fizzbuzz_v1_1.py
Optimized w/ range and fewer if iterations.
=> Updated using range function

students/csdotson/lesson02/README.rst, students/csdotson/lesson02/fizz_buzz.py, students/csdotson/lesson02/print_grid.py, students/csdotson/lesson02/series.py
There should be 4 files submitted:
1) README.rst
2) print_grid.py
3) fizz_buzz.py
4) series.py
=> csdotson: Submitting Lesson #2 Assignments

students/JerryH/Lesson04/mailroom2.py
@natasha-aleksandrova Could you check if I am on the right track so far? Just want to check it with you before I start writing for the second part of the assignment. Thanks
=> Adding mailroom2.py

students/JeroenSweerts/Lesson2/series.py
Please review the code of the series.py file for Fibonacci and lucas series.
Thanks.
Jeroen
=> commiting the fibonacci and lucas series code.

students/Chris_Kenyon/Lesson_2/PrintGrid.py
My loops in activity 3 felt clunky, interested in thoughts on cleaning that up
=> Lesson 2, Activity 1: Creating grids

students/Dustin_L/lesson03/mailroom.py
Addressed comments from previous pull request.
=> Dustin_L - Lesson03 - Mailroom Lab I - Revision

students/Chris_Kenyon/Lesson_2/FizzBuzz.py
I cant tell if the endline is transferring properly per PEP8 guidelines
=> Lesson 2: Activity 2

students/alexLaws/lesson02/fizzBuzz.py, students/alexLaws/lesson02/grid_printer2.py
I added the fizzBuzz assignment here.  I also made a few cleanup edits to the grid printer file after downloading the pep8 and pyflakes linters.  I think it should be fine now.  I know it's after the fact but if there are any other common errors, would appreciate any feedback!
=> fizzBuzz Assignment

students/etwum/lesson03/slicing.py
=> Lesson 03 - Slicing - Emmanuel Twum

students/alexLaws/lesson02/series.py
=> Series Assignment

students/thorn/00-README.md, students/thorn/lesson02/fizzbuzz.py, students/thorn/lesson02/grid_print.py
I'm sure I put in some unnecessary things but it was fun including things like if name == main.  Any feedback or improvements would be great!
=> assignment2 part 1 - grid pull request

students/rhamersky/README.rst
Adding my personal directory to the Self_Paced-Online student directory.
=> Adding Student Folder

students/WesleyM/Lesson2/FizzBuzz.py, students/WesleyM/Lesson2/Print_Grid.py
=> Added Print_Grid.py and FizzBuzz.py

students/tri_nguyen/lesson03/slicing.py
I might have misunderstood part 5 of this exercise which asks to return a sequence with the middle third, the last third, then the first third in the new order.
I am not sure why
+assert mid_last_first(a_string) == 'is a stringthis' <-- AssertionError
+assert mid_last_first(a_tuple) == (13, 12, 5, 32, 2, 54) <-- this passes
when print(mid_last_first(a_string)), the output is 'is a stringthis'.
=> submit slicing.py

students/JamesTraub/README.rst, students/JamesTraub/break_me.py
My git setup is complete, I added my student folder, a readme, and the lesson one break_me.py file.
=> GIT setup complete

students/stuartkershaw/.gitignore, students/stuartkershaw/lesson02/fizzbuzz.py, students/stuartkershaw/lesson02/print_grid.py, students/stuartkershaw/lesson02/series.py
I wanted to make the same function achieve both grid versions, but found the argument ordering made that a little ugly. To keep aligned with the assignment directions, I broke it up into two functions as directed.
=> Lesson 02 Assignments

students/tri_nguyen/lesson03/list_lab.py
Hi Natasha,
I am submitting my list_lab.py.
My while loop in Series 3 is clunky. Maybe you can show me a better way to achieve it.
=> submitting list_lab.py

students/alexLaws/lesson03/list_lab.py
=> My List Lab Assignment

students/tri_nguyen/lesson03/list_lab.py
I cleaned it up a bit. It is a bit better organized.
Thanks for your help.
=> Resubmitting list_lab.py

students/alexLaws/lesson03/strformat_lab.py
=> My String Format Lab Assignment

students/thorn/lesson02/fizzbuzz.py, students/thorn/lesson02/series.py
Added the finished version of series.py.  I also fixed a type in fizzbuzz that had mislabeled what multiples do what.  Code was unaffected.
=> Added series.py - finished.

students/sbolsen/lesson02/grid_print.py
Adding grid printer exercise file for Lesson02
=> Adding grid printer exercise file

students/tri_nguyen/lesson03/strformat_lab.py
I am not sure if I did task six extra correctly. Please let me know if it is wrong.
=> submitting strformat.py

students/shibin_mathew/lesson2/series.py
Created a series.py file which contains a function to compute the fibonacci sequence, lucas sequence and a generalize function to compute both sequences.
=> Fibonacci Series Assignment

students/nDruP/lesson04/Andrew_Park_2018_02_10.txt, students/nDruP/lesson04/Bobson_Dugnutt_2018_02_09.txt, students/nDruP/lesson04/Bobson_Dugnutt_2018_02_10.txt, students/nDruP/lesson04/Mike_Truk_2018_02_09.txt, students/nDruP/lesson04/Mike_Truk_2018_02_10.txt, students/nDruP/lesson04/Rey_McScriff_2018_02_09.txt, students/nDruP/lesson04/Rey_McScriff_2018_02_10.txt, students/nDruP/lesson04/Sleve_McDichael_2018_02_09.txt, students/nDruP/lesson04/Sleve_McDichael_2018_02_10.txt, students/nDruP/lesson04/TaoTeChing.txt, students/nDruP/lesson04/Todd_Bonzalez_2018_02_09.txt, students/nDruP/lesson04/Todd_Bonzalez_2018_02_10.txt, students/nDruP/lesson04/Willie_Dustice_2018_02_09.txt, students/nDruP/lesson04/Willie_Dustice_2018_02_10.txt, students/nDruP/lesson04/sample.txt, students/nDruP/lesson04/sherlock.txt, students/nDruP/lesson04/sherlock_small.txt, students/nDruP/lesson04/trigram.py, students/nDruP/lesson04/trigram.py~, students/nDruP/lesson04/trigram_TaoTeChing.txt, students/nDruP/lesson05/except_exercise.py, students/nDruP/lesson05/except_test.py
Finished the trigram assignment
=> Andrew Park Lesson 4 | Trigram assignment

students/etwum/lesson03/list_lab.py
=> Lesson 03 - Emmanuel Twum - List Lab

students/ghassan/lesson03/fruits.py, students/ghassan/lesson03/slicing.py, students/ghassan/lesson03/str_format.py
I'm not entirely sure what middle third, last third and first third mean. I solved based on what I "think" they mean :)
=> lesson03 - thirds

students/tri_nguyen/lesson03/mailroom.py
Hi Natasha,
For this exercise, I did not know a good way to sort values within nested lists. As a result, of course, I googled and found a way. You will see it on line #84 and #98. I felt that I cheated because the exercise said: "Finally, use only functions and the basic Python data types you’ve learned about so far. There is no need to go any farther than that for this assignment."
Maybe, you can show me how to sort without "itemgetter".
In addition, I tried:
**full_name = input('Enter a Full Name (or type "list" to get the list of donors): ').title()**
for some reason, it didn't take. So had to do:
**full_name.title()** in each if block.
Thanks,
Tri
=> submitting mailroom.py

students/NatalieRodriguez/README.rst, students/NatalieRodriguez/READ_ME.md.txt, students/NatalieRodriguez/READ_ME.txt
Test Pull Request to make sure Git is set up correctly.
=> ReadMe Test Pull Request

students/WesleyM/Lesson3/ListLab.py, students/WesleyM/Lesson3/SlicingLab.py
While submitting Listlab.py Series 3, I noticed that when I tried deleting from my list in my for loop, it would skip the next element. As a result, I used a reverse function to start from the end of my list going backward, but I was curious if there is a way to use the .remove function while going forward?
=> Submitting Listlab.py and correcting SlicingLab.py

students/JamesTraub/Lesson01/break_me.py, students/JamesTraub/Lesson02/JT-Fizz-Buzz.py, students/JamesTraub/Lesson02/grid_printer.py, students/JamesTraub/Lesson02/grid_printer2.py
I am adding the Lesson 2 Grid Printer files grid_printer.py and grid_printer2.py. I created a copy of break_me.py and put it in the Lesson 01 folder. I plan to remove the other break_me.py located in the students/jamestraub folder where my README is located for cleanup.
=> Lesson 2 Grid Printer files

students/MikeShand/lesson03/mailroom.py
Looking at other examples definitely helped a lot
=> First swing at Mailroom

students/alexLaws/lesson03/mailroom.py
I spoke with Natasha mid last week before I went on vacation about this assignment. I had done the full assignment more or less and then saw that it said not to use topics we hadn't covered yet. I'd already written it using dictionaries.  She said that would be ok and I should make a note of it here.
=> My First Mailroom Assignment

students/MikeShand/lesson03/mailroom.py
I couldn't figure out how to get the PEP8 linter working in Sublime, and the web based version I found was less than helpful, so I just used PyCharm. I like Sublime, but PyCharm seems pretty awesome. Are there any known drawbacks to using one over the other?
=> Updated with recommended changes

students/preactive/Lesson2/series.py, students/preactive/Lesson3/slice.py
Was trying to play with yield with fib function in last lesson.  Is there a better way to adjust variables in function with Yield and not use global variables?
Is asserts inline acceptable in the fashion I did them?
=> Finished slice with testing.

students/HarveyHerela/lesson05/README.md, students/HarveyHerela/lesson05/except_exercise.py, students/HarveyHerela/lesson05/mailroom3.py, students/HarveyHerela/lesson05/template.txt
My previous attempt at submitting the exceptions exercise failed, so ignore the GitHub link on the startlearning website for exceptions. This commit here, this pull-request, contains both the exceptions and the mailroom3.
=> Herela: Lesson 5: exception, mailroom3

students/etwum/lesson03/mailroom.py
=> Lesson 03 - Emmanuel Twum - mail room

students/JeroenSweerts/Lesson3/Slicing_Lab_Exercise.py
Please review this code for the Slicing Lab Exercise.
Thanks.
Best regards,
Jeroen
=> commit for submitted code, ready for review

students/alexLaws/lesson04/dict_lab.py, students/alexLaws/lesson04/mailroom.py
Code for the dict Lab and File Lab.
=> Lesson04 Activity

students/etwum/lesson03/mailroom.py
made some updates to the mailroom program based on feedback
=> Emmanuel Twum - updated mailroom program code for lesson 3

students/JeroenSweerts/Lesson3/List_Lab_Exercise.py, students/JeroenSweerts/Lesson3/Slicing_Lab_Exercise.py
Hi,
As suggested after reviewing my code, I rewrote the code applying only slicing.
Could you please review?
Thanks.
Jeroen
=> code with only slicing

students/itsabhi/Lesson2/series.py
This contains functions for Fib, Lucas and sum_series. Added assert towards the end of the main function.
=> Lesson 2 series assignment

students/Dustin_L/lesson05/except_exercise.py, students/Dustin_L/lesson05/except_test.py
Exceptions assignment completed.
=> Dustin_L - Lesson05 - Exceptions Assignment

students/Dustin_L/lesson05/mailroom3.py
Mailroom 3 assignment complete.
Let me know any feedback you have on improving the code or making it more pythonic. Particularly, checking against a return value of None on lines 174 and 178. Thanks!
=> Dustin_L - Lesson05 - Mailroom3

students/etwum/lesson04/mailroom_part2.py
=> Lesson 04 - Emmanuel Twum - Mailroom Part 2

students/JeroenSweerts/Lesson3/List_Lab_Exercise.py
Hi,
Please review my code for the List Lab Exercise. I tried to make the file name all lowercase letters as recommended, but somehow it still shows up in camel case in the GitHub repository.
Thanks.
Best regards,
Jeroen
=> first commit for List Lab excercise

students/Matt_Hudgins/Lesson02/Grid_Printer.py, students/Matt_Hudgins/Lesson02/Test.py
Hopefully this works without submitting 52 file changes.
=> Lesson02 Part1 Complete

students/JeroenSweerts/Lesson3/string_formatting_exercise.py
Hi, 
Please review my code for the String Formatting Exercise.
Thanks.
Best regards,
Jeroen
=> first commit for String Formatting Exercise

students/etwum/lesson05/except_exercise.py, students/etwum/lesson05/except_test.py
except handling exercise complete
=> Lesson05 - Emmanuel Twum - Exceptions Exercise

students/mayc4t/00HelloGit/HelloGit.py, students/mayc4t/README.md
Added my account: mayc4t
Add my 00 non assigned first check in
=> Added my first checkin to test git. Not a real assignment yet

students/idcrickmore/lesson02/fizz_buzz.py
Updated file name and code to pep8 guidelines per Natasha's comments.
-IDC
=> Updated fizzbuzz.py 

students/csdotson/lesson03/list_lab.py, students/csdotson/lesson03/mailroom.py, students/csdotson/lesson03/slicing_lab.py
Thanks a lot for the suggestions, Natasha! I tried to incorporate everything you had mentioned. Let me know if you still see any issues.
=> Lesson03 incorporate suggested fixes

students/thorn/lesson03/list_lab.py, students/thorn/lesson03/slicing_basics.py
Question: why does my first4/last4/everyother function produce that ','?  I couldn't manage to slice it and get the comma manually.
=> Pull request for 1 - Slicing

students/JeroenSweerts/Lesson3/mailroom.py
Please review the recommended updates. I couldn't make it work to switch to an alternative data structure without making the code complexer and without using dictionaries. So I kept the data structures that I initially used.
Thanks.
Jeroen
=> second commit

students/WesleyM/Lesson3/StringFormatLab.py
Submitting Lab 3 String Formatting Lab Assignment
=> Submitting StringFormatLab.py

students/tri_nguyen/lesson04/sherlock_small.txt, students/tri_nguyen/lesson04/trigrams.py
Hi Nathasha or Rob,
For some unknown reason, I found this exercise difficult. It took me a long time, and it still not perfect.
Is there a cleaner, better way to accomplish this exercise?
=> submitting trigrams.py

students/idcrickmore/lesson02/series.py
Please review my series.py submission. Also please grade my Fizzbuzz.py submission.
Thank you,
Ian David Crickmore
=> lesson02 series.py

students/TinaB/README.rst, students/TinaB/lessonOne_TB/break_me.py, students/TinaB/lessonTwo_TB/lesson2.py
Adding student folder, and lessons one and two assignments.
=> Adding TinaB Student Folder and lessons One and Two

students/csdotson/lesson04/mailroom_2.py
Completed mailroom_2.py for Lesson04.
=> Lesson04 mailroom part2

_config.yml, students/preactive/Lesson2/series.py, students/preactive/Lesson3/list_lab.py, students/preactive/Lesson3/slice.py, students/preactive/Lesson3/strformat_lab.py
List lab submission and fixes for PR 169.
let me know what you think of the mod i made on line 24 here: https://github.com/UWPCE-PythonCert-ClassRepos/Self_Paced-Online/commit/9c3e61a931a70719e1e9118be68ad0a3f2cd1587#diff-b3e27a23e5fea67b49894d5c5caad2e8R24
and the testing asset fix for PR 169
=> Lesson 3 List lab

students/NatalieRodriguez/Lesson02/sequences.py
I'm not sure I did the assert statements correctly. It did not throw an exception, so I assumed they went through alright.
=> lesson02 fib, lucas, and sum series assignment

students/nDruP/lesson06/mailroom4.py, students/nDruP/lesson06/mailroom4.py~, students/nDruP/lesson06/run_mailroom4.py, students/nDruP/lesson06/test_mailroom4.py, students/nDruP/lesson06/test_mailroom4.py~
This one really confused me. 
Please let me know if I've refactored the correct parts of my code to make them more test-friendly.
If not, I definitely need some more insight to the decision making behind what to refactor.
=> Lesson 6: Testing & refactoring mailroom

students/khtruong/lesson_03/list_lab.py, students/khtruong/lesson_03/mailroom.py, students/khtruong/lesson_03/slicing_lab.py, students/khtruong/lesson_03/strformat_lab.py, students/khtruong/lesson_04/00-README.srt, students/khtruong/lesson_04/dict_lab.py, students/khtruong/lesson_04/file_lab.py, students/khtruong/lesson_04/mailroom_v2.py, students/khtruong/lesson_04/sherlock_small.txt, students/khtruong/lesson_04/trigrams.py
Also addressed Rob's comment for lesson_03.
=> lesson_04 submission

students/alexLaws/lesson05/mailroom.py
Here's my mailroom file for lesson 5. I added one comprehension but there weren't many obvious places for me to add it given how I've approached the mailroom work so far.
=> Mailroom Lesson 5

students/MikeShand/lesson04/code_kata/sherlock.txt, students/MikeShand/lesson04/code_kata/sherlock_small.txt, students/MikeShand/lesson04/code_kata/trigrams.py, students/MikeShand/lesson04/mailroom_switch.py
Thank you Natasha for your generous donation of 1000!
Please accept our thanks, and this honorary membership in the fruitcake of the month club.
=> Uplaoded with more refinements

students/tri_nguyen/lesson05/mailroom.py
Hi Natasha,
I made some changes that you suggested in merged #220.
=> submit mailroom.py

students/ghassan/lesson05/new_mailroom.py
I used try and except in send_thankyou method, however it seems like the code block after the exception is always executed regardless if the key exists in the dictionary or not. I'm not sure why. 
Can you please help me out on that one. Thanks!
=> lesson05 - new_mailroom - exceptions

students/JeroenSweerts/Lesson4/bobonne.txt, students/JeroenSweerts/Lesson4/bompa.txt, students/JeroenSweerts/Lesson4/dict_lab.py, students/JeroenSweerts/Lesson4/file_lab.py, students/JeroenSweerts/Lesson4/jeroen.txt, students/JeroenSweerts/Lesson4/mailroom2.py, students/JeroenSweerts/Lesson4/mama.txt, students/JeroenSweerts/Lesson4/onbekende.txt, students/JeroenSweerts/Lesson4/papa.txt
Hi, 
Please review my code for the Mailroom Part 2 assignment.
Thank you.
Jeroen
=> Assignment: Mailroom, Part 2

students/MikeShand/lesson05/mailroom3.py
couldn't find a sensible place to add list comprehensions
=> Exception handling in mailroom3

students/JeroenSweerts/Lesson4/kata.py, students/JeroenSweerts/Lesson4/sherlock.txt
Hi, 
Please review my code for the Kata Fourteen assignment.
Not sure why I keep getting a 'b' in front of each word.
Thanks.
Jeroen
=> first commit of Kata exercise

students/NatalieRodriguez/Lesson03/list_lab.py
This was a really fun assignment that I learned a lot from!
=> Lesson 03, Series 1-4

students/JeroenSweerts/Lesson4/kata.py, students/JeroenSweerts/Lesson5/except_exercise.py, students/JeroenSweerts/Lesson5/except_test.py
Hi,
Please review my code for the Exceptions Exercise. I don't get the exact same result as the output that is expected in the outline. Not sure if this is a typo on the website or if I have an error in my code.
Thanks.
Jeroen
=> First commit for Exception Exercise

students/etwum/lesson06/Lionel Messi.txt, students/etwum/lesson06/mailroom_part4.py, students/etwum/lesson06/test_mailroom.py
=> Lesson 06 - Emmanuel Twum - Mailroom Part 4

students/JeroenSweerts/Lesson5/mailroom3.py
Hi, 
Could you please review my code for the mailroom assignment of Lesson 5?
Thanks.
Best regards,
Jeroen
=> Lesson 5 Mailroom Exercise

students/csdotson/lesson05/mailroom_3.py
Just wanted to incorporate the suggestions you had. Probably no need for much feedback unless you see something glaring. Thanks!
=> Lesson5 - Mailroom3: Incorporate instructor suggestions

students/tri_nguyen/lesson06/mailroom.py, students/tri_nguyen/lesson06/test_mailroom.py
Natasha,
I made changes per your advice in #287  to mailroom.py and used dict for values as well.
I did:
+    donor_name = enumerate([donor for donor in donor_dict])
+    for idx, name in donor_name:
+        print(idx + 1, '-', name)
because I wanted to use the index number to list donor names.  For example:
1 - William Gates, III
2 - Mark Zuckerberg
3 - Jeff Bezos
4 - Paul Allen
5 - Tri Nguyen
Is there a better way to do it without enumerating?
With regard to test_mailroom.py, I am not sure how to test functions that print. Do I use mock? Could you provide an example of how to test my create_report() function using mock?
Looking forward to your advice and tips.
Thanks,
Tri
=> submt lesson6 files

students/shibin_mathew/lesson3/a_new_file.py
Modified functions to use slicing and used linter to fix Pep-8 violations
=> Modified functions to use slicing

students/thorn/lesson03/mailroom.py
Fixed bug adding duplicate donors.
=> Added suggested edits.

students/elmar_m/lesson05/except_exercise.py, students/elmar_m/lesson05/mailroom.py
Added exception handling to mailroom.py. Additionally i reviewed the code for possibilities to use comprehensions, but i didn't see any without adding some kind of new functionality (e.g. show last two donations of every donor or so...). 
As i think that refactoring my code quite much is necessary anyway to be able to implement decent unittesting, this (use of comprehensions) may be done additionally in one of the following exercises.
Furthermore i added a small change to already assigned and accepted except_exercise.py to reflect Rob's comment on it (thx Rob :).
=> Lesson05: mailroom.py 

students/TrkCat/Lesson01/break_me.py, students/TrkCat/Lesson02/drawGrid.py, students/TrkCat/Lesson02/fizzbuzz.py, students/TrkCat/Lesson02/series.py, students/TrkCat/README.rst
Completed Lesson 2 exercises (and initial break_me.py lesson 1 exercise).
=> Completed Lesson 2 Exercises

students/stuartkershaw/lesson05/mailroom.py
I was able to refactor with improved exception handling. I had a harder time finding a good use for comprehensions though... perhaps it's just the way I've organized things. I was able to do some condensing around line 135 with the zip function, but I'm not sure I would use this in production. Perhaps it would make better sense in a situation where my variable names were different from the key names of the dict I'm building up.
=> Lesson 05 Mailroom

students/WesleyM/Lesson6/mailroom4.py, students/WesleyM/Lesson6/mailroom4_test.py
Changed mailroom3.py into mailroom4.py by:
Separating user input selection into its own function away from main file
Included an if statement in the main file to rerun user input instead of after each menu function
Mailroom4_test.py checks:
Closing the test program prints the closing message
Typing list in option one prints out the expected list of donors
A mock attempt of the main menu adding a person to the donor list and quitting produces the same print out
Printing out the report with the expected result
Typing a correct and incorrect value into the input function produces the expected result
Executing the letters function prints out the expected result and the message inside each file is as expected
=> submitting mailroom4.py and mailroom4_test.py for instructor review

students/JeroenSweerts/Lesson5/bobonne.txt, students/JeroenSweerts/Lesson5/bompa.txt, students/JeroenSweerts/Lesson5/mama.txt, students/JeroenSweerts/Lesson5/onbekende.txt, students/JeroenSweerts/Lesson5/papa.txt, students/JeroenSweerts/Lesson6/mailroom4.py, students/JeroenSweerts/Lesson6/test_mailroom4.py
Hi,
Please review my code for the Mailroom Part 4 assignment.
Thanks.
Best regards,
Jeroen
=> first commit

students/WWhite/Lesson02/Lesson2Assignment.py, students/WWhite/README.md
Creating directory and readme file for William White
=> Added readme file

students/Matt_Hudgins/Lesson02/series.py
=> Part 3 of Lesson 02

students/kmsnyde/lesson2/series.py
Corrected issues in original series.py based on feedback from instructor.
- changed list name from "list" to "fib_list", as an example.
- corrected code to return nth number in sequence, vice n as how many in the sequence to return.  In this case, I only had the algorithm create as many digits, in the fibonacci sequence, for example, as required to produce the nth number.
- updated assertions based on above changes.
=> lesson2 - corrected series.py based on instructor feedback

students/TinaB/lessonTwo_TB/FizzBuzz.py, students/TinaB/lessonTwo_TB/series.py
Adding last two lesson assignments from lesson 2.
=> Adding last two lesson 2 assignments

students/TinaB/lesson03/SlicingLab.py, students/TinaB/lesson03/list_lab.py
Adding list lab and slicing lab assignments for week three.
=> added lesson three list_lab and slicing_lab assignments

students/awilmoth/README.md, students/awilmoth/fizzbuzz.py
=> Adding fizzbuzz

students/shibin_mathew/lesson3/mailroom.py
Fixed all the pep-8 violations and made the fixed the code to be more efficient and readable.
=> Fixed pep-8 violations in mailroom.py and added a user menu.py

students/kmsnyde/lesson3/strformat_lab.py
Some of this was iffy figuring out.  I was able to write the code to accomplish what I thought was being asked, but may have misunderstood the exact semantics of what you actually needed.
=> lesson3 - strformat_lab.py

students/AurelPerianu/Lesson1/break_me.py, students/AurelPerianu/README.rst
first pull request - break_me.py  and readme.rst files
=> Aurel Perianu - Lesson1

students/kmsnyde/lesson3/mailroom.py
Not an easy assignment for; lots of off classroom research where I didn't feel the class documentation helped me to understand and solve the this particular lesson.  Feedback always welcome!
=> lesson3 - mailroom.py

students/rgpag/README.rst
created new student dir with README for Robert Pagliarini
=> new student dir "rgpag" 

students/TinaB/lesson03/SlicingLab.py, students/TinaB/lesson03/list_lab.py, students/TinaB/lesson03/mailroom.py, students/TinaB/lesson03/strformat_lab.py
Updated first two labs based on comments, and adding mailroom and strformat_lab.
=> Adding Lesson Three Mailroom and strformat_lab, updating previous labs

students/Dustin_L/lesson09/mailroom4.py, students/Dustin_L/lesson09/test_mailroom4.py
Completed Lesson09. Any and all feedback welcome!
=> Dustin_L - Lesson09 - Mailroom with classes

students/kmsnyde/lesson04/dict_lab.py, students/kmsnyde/lesson04/mailroom2.py
my mailroom part 2 lesson as mailroom2.py
=> lesson04 - mailroom2.py

students/NatalieRodriguez/Lesson05/except_exercise.py, students/NatalieRodriguez/Lesson05/except_test.py, students/NatalieRodriguez/Lesson05/testing.py
=> exception handling - ready for review

students/NatalieRodriguez/Lesson05/mailroom3.py
Added exception handling for the 'thank_all()' function's 'FileNotFound' Error, provided an error message, and allowed the user another attempt at providing a valid file location.
=> mailroom, part 3, with exception handling added. 

students/tri_nguyen/lesson08/SparseArray_class.py, students/tri_nguyen/lesson08/circle.py, students/tri_nguyen/lesson08/test_circle.py
I made changes per your advice from #448.
For SparseArray, I still don't think I did it correctly to store non-zeros.
=> clean up and resubmit

students/nDruP/lesson08/circle.py, students/nDruP/lesson08/sparse_array.py, students/nDruP/lesson08/test_circle.py, students/nDruP/lesson08/test_sparse_array.py
I forgot to do frequent commits. Overall a pretty straightforward lesson. I would've liked to see how magic methods and properties carry over to subclasses, but we'll probably get to that in a future lesson.
=> Lesson08|circle.py

students/julienjass/Lesson02/fizz_buzz.py
Hello,
I'm just starting submitting my first exercise for the class.
Thanks,
Julien Jasserme
=> Added fizz_buzz for Class02

students/kmsnyde/lesson05/except_exercise.py, students/kmsnyde/lesson05/except_test.py
PR for except.exercise.py (lesson05)
=> lesson05 - except_exercise.py

students/mayc4t/lesson06/mailroom4.py, students/mayc4t/lesson06/mailroom4_test.py
Files:
mailroom4.py
mailroom4_test.py
=> Lesson 06: mailroom with unittest

students/smitco/lesson02/grid.py
grid.py is the lesson 02 assignment parts 1-3
=> Lesson 02 Grids Part 1-3

students/Matt_Hudgins/Lesson03/list_lab.py
=> list lab complete

students/rgpag/lesson03/list_lab.py, students/rgpag/lesson03/mailroom.py, students/rgpag/lesson03/slicingLab.py, students/rgpag/lesson03/strformat_lab.py
cleaned up strformat_lab, list_lab, slicingLab per instructor feedback. Completed mailroom pt 1 for instructor review.
=> L03 Cleanup + mailroom Pt 1

students/smitco/lesson02/fizzbuzz.py, students/smitco/lesson02/series.py
fizzbuzz.py is the lesson 02 fizzbuzz exercise
series.py is the lesson 02 series exercise- this is my first time using assert statements. Are 4 asserts sufficient for checking the code, or would you normally expect to see more asserts?
=> Lesson 02 fizzbuzz and series exercises

students/shibin_mathew/lesson8/.pytest_cache/v/cache/lastfailed, students/shibin_mathew/lesson8/.pytest_cache/v/cache/nodeids, students/shibin_mathew/lesson8/Circle.py, students/shibin_mathew/lesson8/test_Circle.py
Added Circle.py and unit tests (test_Circle.py) for lesson 8
=> Created Circle.py and test_Circle.py for lesson 8

students/csdotson/lesson06/mailroom_4.py, students/csdotson/lesson06/test_mailroom_4.py
**Notes:** Mailroom required a pretty heavy refactor to allow for unit testing. Aside from printing functions and user input, most functionality is covered by testing. Let me know if you see areas to fix/improve.
**Files**:
- mailroom_4.py
- test_mailroom_4.py
=> Lesson6 - Refactored mailroom.py and unit testing

students/shibin_mathew/lesson9/Andreck.txt, students/shibin_mathew/lesson9/Ginger.txt, students/shibin_mathew/lesson9/Jordy.txt, students/shibin_mathew/lesson9/Kimberly.txt, students/shibin_mathew/lesson9/Shibin.txt, students/shibin_mathew/lesson9/mailroom.py, students/shibin_mathew/lesson9/test_mailroom.py
mailroom.py and test_mailroom.py for lesson 9.
=> Updated mailroom.py with OO principles and generated tests

students/rhamersky/Lesson_4/mailroom_part2.py, students/rhamersky/Lesson_5/except_exercise.py, students/rhamersky/Lesson_5/except_test.py, students/rhamersky/Lesson_5/mailroom_part3.py
Lesson 4 assignment 1 and lesson 5 complete.
=> Lesson 4 & Lesson 5

students/Matt_Hudgins/Lesson05/except_exercise.py
=> Completed this exercise

students/NatalieRodriguez/Lesson09/OO_Mailroom.py
I have a try-except block, but it seems that the code at lines 89-92 never gets run, even when the donor name is found in the list. Not sure what I'm missing to get it to run this chunk.
=> lesson 09 -- OO Mailroom

students/itsabhi/Lesson7/html_render.py, students/itsabhi/Lesson7/test_html_output8.html, students/itsabhi/Lesson7/test_html_render.py
This was probably my favorite exercise..I found myself struggling with the whole Duck typing concept (Step 2) particularly, but hopefully I think I'm getting a hang of it.
=> Lesson 7: HTML Render exercise

students/kmsnyde/lesson03/mailroom.py, students/kmsnyde/lesson06/test_mailroom5_classes.py, students/kmsnyde/lesson09/mailroom5_classes.py, students/kmsnyde/lesson09/test_mailroom5_classes.py
Had a difficult time with mostly with setting it up and finally used a dictionary after much research but I think I took the long way around some areas.  Slim on being able to use TDD because of my troubles I sort of troubleshot along the way hitting F5 a thousand time and making updates.
=> lesson09 mailroom with classes

students/rfelts/lesson02/fizz_buzz.py
Submitting the fizz buzz file for assignment 2. Pretty straight forward code so I didn't make any comments.
=> Adding the Fizz Buzz file for assignment 2

students/Matt_Hudgins/Lesson05/mailroom_3.py
Added exceptions to mailroom assignment
=> Exceptions Assignment

students/WWhite/lesson04/Mailroom.py
=> Mailroom V2

students/TinaB/lesson07/html_render.py, students/TinaB/lesson07/run_html_render.py, students/TinaB/lesson07/test_html_render.py
Adding lesson 07 files: Test_html_render, html_render, and run_html_render files.
I don't believe my tests were robust enough - but I also didn't want to spend days just working on this testing file.
=> Lesson07 Assignment - HTML Render

students/kmsnyde/lesson09/mailroom5_classes.py, students/kmsnyde/lesson10/mailroom6_functional.py
I refactored my classes from lesson 9 based on instructor feedback to have more of my methods in the Donors class vice Donor (as I now understand why).
The latest lessons work is captured in menu item 4, "Projections" and will allow for input of a factor, and min/max contribution limits.
=> lesson10 - mailroom_refactored class and func programming

students/MicahBraun/Lesson 03/mailroom.py
Updated sequence to update search terms so that duplicate name entries for new entries will flag.
=> Updated: search names enhanced to capture duplicates

students/Matt_Hudgins/Lesson06/mailroom_4.py, students/Matt_Hudgins/Lesson06/mailroom_4_unittest.py
Two files one for mailroom_4.py and one for the unit test mailroom_4_unittest.py
=> Unittest Assignment

students/BrandonHenson/Lesson10/Mailroom_6.py
Thank you. Natasha and Rob for this class. I feel like a learned a lot.
=> Finshed FP

students/TinaB/lesson08/circle.py, students/TinaB/lesson08/lesson08Activity.py, students/TinaB/lesson08/test_circle.py
=> Lesson 08 Assignments

students/idcrickmore/lesson08/circle.py, students/idcrickmore/lesson08/test_circle.py, students/idcrickmore/lesson09/mailroom_pt5.py
Please review circle.py and test_circle.py.
thank you,
IDC
=> lesson08 ready for review

students/TinaB/lesson09/mailroom.py, students/TinaB/lesson09/test_mailroom.py
Adding lesson 09 assignment and test files. Started out doing separate files and then combined it all in one script. Refactored the mailroom code to include the two recommended classes, and tried to remove all inputs/user interactions to outside the classes.
=> adding lesson 09 assignment and test files

students/rob_sanchez/README.rst
Adding new directory for my code and initial README file.
=> Created a new readme file.

students/Matt_Hudgins/Lesson06/mailroom_4_unittest.py, students/Matt_Hudgins/Lesson07/html_render.py, students/Matt_Hudgins/Lesson07/test_html_render.py, students/Matt_Hudgins/Lesson08/circle.py
=> HTML Render and Test

students/mayc4t/lesson09/mailroom5.py, students/mayc4t/lesson09/test_mailroom5.py
File submitted: mailroom5.py
test_mailroom5.py
Use autopep -i for all files.
=> Lesson 09: Done and ready for review

students/ador_yano/README.rst
Testing my Git/GitHub workflow by adding my student directory ("ador_yano") with a test README file.
=> my student directory and added a readme file

students/TinaB/lesson10/mailroom_fp.py
Adding mailroom final assignment.
=> Lesson 10 Mailroom Assignment

students/mkdir01/lesson02/grid_printer_final.py
mkdir01/lesson02/grid_printer_final.py
=> added file for lesson 2: grid printer

students/mkdir01/lesson02/Fizz_buzz.py, students/mkdir01/lesson02/grid_printer_final.py
mkdir01/lesson02/grid_printer_final.py
=> made recommended fixes to lesson 2: grid printer

students/smitco/lesson03/list_lab.py, students/smitco/lesson03/mailroom_draft.py, students/smitco/lesson03/slicing.py, students/smitco/lesson03/strformat_lab.py
The first 3 exercises for lesson 03- slicing, list, string formatting
=> Slicing, list, and string formatting labs for lesson 03

students/mkdir01/lesson02/Fizz_buzz.py, students/mkdir01/lesson02/series.py
=> made fixes to lesson 2: fizz_buzz and added lesson 2: fibonacci_series

students/Wieslaw_Pucilowski/README.rst, students/Wieslaw_Pucilowski/lesson01/break_me.py, students/Wieslaw_Pucilowski/lesson02/FizzBuzz.py, students/Wieslaw_Pucilowski/lesson02/grid_printer.py, students/Wieslaw_Pucilowski/lesson02/series.py
lesson01:
break_me.py
and 
lesson02 assignment:
grid_printer.py
FizzBuzz.py
series.py
=> Lessoc02 assignement

students/WWhite/lesson04/trigrams.py, students/WWhite/lesson05/Mailroom.py, students/WWhite/lesson05/except_exercise.py, students/WWhite/lesson05/except_test.py
Accidentally included the Mailroom assignment. Nothing has changed from what is included here and what was included in the previous pull request for the Mailroom file.
=> Creating pull request for Trigrams and Exceptions assignments

students/stefanjp1/README.rst, students/stefanjp1/lesson02/fizzbuzz.py, students/stefanjp1/lesson02/print_grid.py, students/stefanjp1/lesson02/series.py
Added lesson02 script to turn in.
=> Set up github for Stefan Partin

students/idcrickmore/lesson09/mailroom_pt5.py, students/idcrickmore/lesson09/test_mailroom_pt5.py
Please review mailroom_pt5.py and test_mailroom_pt5.py
thanks,
Ian David
=> assignment 9 comlete

students/MicahBraun/Lesson 04/Markov_Analysis.py, students/MicahBraun/Lesson 04/Random.txt
Trigram program written, text file included for example
=> Lesson 4, Markov/ Trigram

students/rgpag/lesson06/test_mailroom.py
added test_mailroom.py for L06 review.
=> added test_mailroom.py

students/mkdir01/lesson03/slicing.py
=> added lesson 3 - slicing lab

students/stefanjp1/lesson03/ex1.py, students/stefanjp1/lesson03/list_lab.py, students/stefanjp1/lesson03/mailroom.py, students/stefanjp1/lesson03/strformat_lab.py
=> Work from lesson 03

students/mkdir01/lesson03/list_lab.py
=> fixed slicing lab and added list lab

students/rob_sanchez/Lesson 3/Slicing.py, students/rob_sanchez/Lesson 3/list_lab.py
Completed Slicing Lab exercise.
=> Slicing Lab Exercise

students/mkdir01/lesson03/strformat_lab.py
list_lab.py and strformat_lab.py
=> made fixes to list_lab.py based on feedback, added strformat_lab.py

students/AurelPerianu/Lesson3/list_lab.py, students/AurelPerianu/Lesson3/mailroom_1.py, students/AurelPerianu/Lesson3/slices_lab.py, students/AurelPerianu/Lesson3/string_lab.py, students/AurelPerianu/Lesson4/mailroom_2.py, students/AurelPerianu/Lesson4/trigrams.py, students/AurelPerianu/Lesson5/except_exercise.py, students/AurelPerianu/Lesson5/except_test.py, students/AurelPerianu/Lesson5/mailroom_3.py
I had these files but I didn't push them. I believe I followed all the instructions, but if you find something not working, please let me know. I use Jupyter notebooks to develop the scripts and sometimes the text doesn't align correctly when I copy the code in Atom. All the scripts work when I run them from terminal.
=> Added lessons 3,4,5

students/mkdir01/lesson03/list_lab.py, students/mkdir01/lesson03/mailroom.py, students/mkdir01/lesson03/slicing.py
=> added lesson03 - Mailroom as mailroom.py

students/tfbanks/00-ReadMe.md, students/tfbanks/lesson01/break_me.py
Just finished setting up environment setup and first exercise.  looking forward to lesson 2.
=> Loading ReadMe file and lesson01 break_me.py file

students/mkdir01/lesson04/mailroom2.py
=> 2nd mailroom assignment, incorporated feedback from 1st mailroom

students/stefanjp1/lesson04/Untitled.ipynb, students/stefanjp1/lesson04/copy_file.py, students/stefanjp1/lesson04/dict_lab.py, students/stefanjp1/lesson04/display_files.py, students/stefanjp1/lesson04/mailroom.py, students/stefanjp1/lesson04/trigram.py, students/stefanjp1/lesson04/wish_test.txt
=> lesson04 work

students/mkdir01/lesson04/Trigram_Kata.py
=> fixes to mailroom2 and added lesson 4 - Trigram Kata

students/Sean_Tasaki/Lesson08/circle.py, students/Sean_Tasaki/Lesson08/test_circle.py
Lesson08 Assignment Scripts ready for review :)
=> Lesson08 Assignment ready for review

students/MicahBraun/Lesson 05/except_exercise.py, students/MicahBraun/Lesson 05/except_test.py, students/MicahBraun/Lesson 05/mailroom_3.py
Exercise completed. Message prints out
"Whoops! there is no joke for: spam
Customer: Not much of a cheese shop really, is it?
Shopkeeper: Finest in the district, sir.
Customer: And what leads you to that conclusion?
Shopkeeper: Well, it's so clean.
Customer:  It's certainly uncontaminated by cheese."
=> Lesson 05, Exception Exercise

students/Wieslaw_Pucilowski/lesson05/except_exercise.py, students/Wieslaw_Pucilowski/lesson05/mailroom3.py
Lesson05 assignment - except_exercise.py, mailroom3.py
=> Lesson05 assignment - except_exercise.py, mailroom3.py

students/Wieslaw_Pucilowski/lesson05/mailroom3.py
=> lesson05 updated mailroom3.py

students/mkdir01/lesson05/except_exercise.py, students/mkdir01/lesson05/except_test.py
=> lesson 5 exception exercise

students/tfbanks/Lesson02/fizzbuzz.py
=> Submitting Lesson 2 exercise 2 - FizzBuzz

students/AurelPerianu/Lesson6/Donor A.txt, students/AurelPerianu/Lesson6/Donor B.txt, students/AurelPerianu/Lesson6/Donor C.txt, students/AurelPerianu/Lesson6/Donor D.txt, students/AurelPerianu/Lesson6/Donor E.txt, students/AurelPerianu/Lesson6/Donor F.txt, students/AurelPerianu/Lesson6/mailroom_4.py, students/AurelPerianu/Lesson6/test_mailroom_4.py
I used pep8 to check the files. I think there are no formatting issues.
=> added lesson6

students/toddschultz/README.rts, students/toddschultz/session02/print_grid.py
Pull request for the readme file and my homework for session 2. So far so good ... I hope.
=> Hello first pull request world!

students/toddschultz/session03/slicing_lab_exercise.py
I forgot to make frequent commits as I was working on the assignment, I will try and get better at that on future assignments. 
Feedback from last time was that my code was over indented, I believe I have fixed that by making my tab 4 spaces. I need to find out how to do that by default in Sublime 2, as each new file reverts back to actual tabs. 
I believe that is all.   --toddschultz
=> Session03 assignment #1.

students/SLammertink/Lesson02/FizzBuzz.py, students/SLammertink/Lesson02/series.py
Hi, I messed up my first pull request due to some issues with Github, so I cannot upload the FizzBuzz exercise at its proper place so have to do it here!
Hope this is ok.
Best regards,
Sebastiaan Lammertink
=> Added the Fizzbuz exercise and series exercise from Lesson 02

students/mkdir01/lesson05/mailroom3.py
=> lesson 5, mailroom 3

students/ptfbanks/Lesson02/Fib-01.py, students/ptfbanks/Lesson02/Fib-02.py, students/ptfbanks/Lesson02/FibFinal.py, students/ptfbanks/Lesson02/FizzBuzz.py, students/ptfbanks/READptf.md
In keeping with request for showing developmental work I have recorded first and second iterations of work; 1 to develop the core Fibonacci and Lucas series, 2 to incorporate function to respond with a request position value of either series.  The final script incorporates the sum_series function as requested and incorporates assert tests.
By virtue of design selected I had to apply my inserts into the body of the final program rather than at the appended section as requested.  That factor was noted in commented assertions in the validation section.
=> Submitting assignments for lesson 2 - Pete Fairbanks (ptfbanks) 7-1-18

students/toddschultz/session03/list_lab.py, students/toddschultz/session03/slicing_lab_exercise.py
I've updated the Slicing Lab Exercise with feedback from the instructors, including: 
1. Removing the function calls
2. Removing the duplicate functions
3. Adding Asserts. 
This is also the initial turn in for the second homework, List Lab.
=> Lesson 3 assignments; lesson 1 updated, lesson 2 initial request. 

students/ABartles/Exercise2/FizzBuzz.py, students/ABartles/Exercise2/GridPrinter.py, students/ABartles/Exercise2/Series.py, students/ABartles/Test/TestFile.py
Please review the Exercise 2 files and let me know if there are any concerns or areas of improvement. Thank you.
=> Exercise 2 For Review - Bartles 

students/WWhite/lesson06/mailroom4.py, students/WWhite/lesson06/test_mailroom4.py, students/WWhite/lesson07/html_render.py, students/WWhite/lesson08/circle.py
Pull request with unit test, html renderer, and circle class assignments
=> Unit Testing, Html Renderer, Circle Class

students/rgpag/lesson08/circle_class.py, students/rgpag/lesson08/test_circle.py
please review "circle_class.py" for lesson 08
=> lesson 08 for review

students/mkdir01/lesson06/mailroom3.py, students/mkdir01/lesson06/test_mailroom.py
mailroom3.py and test_mailroom.py
=> refactored mailroom and test suite

students/SLammertink/Lesson03/list_lab.py
This is my solution to the list_lab.py exercise
=> Added the Lesson03 list_lab.py exercice

students/tfbanks/Lesson02/fibonacciseries.py, students/tfbanks/Lesson02/fizzbuzz.py, students/tfbanks/Lesson02/series.py
adding series.py for your review.
FYI, I also updated fizzbuzz.py with instructor suggestion - added range(1,n+1) to function so it starts at 1 and not 0 as previously submitted.
=> adding series.py to lesson 2 

students/WWhite/lesson09/oo_mailroom.py
Pushing final version of OO Mailroom
=> OO Mailroom

students/KevinWaldron/README.rst, students/KevinWaldron/lesson02/fizz_buzz.py, students/KevinWaldron/lesson02/print_grid.py, students/KevinWaldron/lesson02/series.py
Added my student directory, a readme and the .py files for the 3 assignments for lesson 2.
=> Kevin Waldron Lesson 2 assignments

students/rgpag/lesson09/mailroom.py, students/rgpag/lesson09/mailroom_classes.py, students/rgpag/lesson09/test_mailroom.py
please review lesson09 mailroom.py, mailroom_classes.py, test_mailroom.py
=> lesson09 for review

students/Wieslaw_Pucilowski/lesson06/test_mailroom4.py
please find updated test_mailroom4.py
=> updated test_mailroom4.py

students/SLammertink/Lesson03/mailroom_1.py, students/SLammertink/Lesson03/strformat_lab.py
Added the strng formatting lab from lesson 03.
=> Added the string formatting lab

students/AndyKwok/lesson03/Slicing.py
Submission of Lesson 03 Ex 1 & 3. 
Please let me know if there are any issues or corrections needed. 
Thank you
=> Lesson 03 - Ex 1, 3

students/rfelts/lesson03/mailroom.py
I'm now using PyCharm. So hopefully I'm more PEP8 compliant now. 
Also I added a try - except block in the prompt_donation_amount function. But I didn't use a basic Python exception or create a special exception like I would in Java. I'm assuming exceptions and exception handling will be covered in a later lesson/class.
=> Here's the mailroom file for assignment 3.

students/Wieslaw_Pucilowski/lesson07/html_render.py, students/Wieslaw_Pucilowski/lesson07/run_html_render.py, students/Wieslaw_Pucilowski/lesson07/test_html_render.py
=> Lesson07 assignment

students/ABartles/Exercise2/GridPrinter.py, students/ABartles/Exercise2/Series.py, students/ABartles/Exercise3/Mailroom.py, students/ABartles/Exercise3/SlicingLab.py, students/ABartles/Exercise3/StringFormatting.py, students/ABartles/Exercise3/list_lab.py
Pull request for exercise 3 assignments. 
Please let me know if there are any issues or items I should work on.  Thank you for your time.
=> Exercise 3 Assignments

students/smitco/lesson06/mailroom4.py, students/smitco/lesson06/test_mailroom4.py
Minor updates to mailroom4 and completed pytest file. Please let me know if there are any other sections of mailroom that should have tests done.
=> Lesson 06 mailroom4 and pytest file

students/stefanjp1/lesson07/.pytest_cache/v/cache/lastfailed, students/stefanjp1/lesson07/.pytest_cache/v/cache/nodeids, students/stefanjp1/lesson07/html_render.py, students/stefanjp1/lesson07/run_html_render.py, students/stefanjp1/lesson07/sample_html.html, students/stefanjp1/lesson07/simple_classes.py, students/stefanjp1/lesson07/test_html_output1.html, students/stefanjp1/lesson07/test_html_output2.html, students/stefanjp1/lesson07/test_html_output3.html, students/stefanjp1/lesson07/test_html_output4.html, students/stefanjp1/lesson07/test_html_output5.html, students/stefanjp1/lesson07/test_html_output6.html, students/stefanjp1/lesson07/test_html_output7.html, students/stefanjp1/lesson07/test_html_output8.html, students/stefanjp1/lesson07/test_html_render.py
=> adding lesson07 work

students/Wieslaw_Pucilowski/lesson07/html_render.py
class Html(Element):
Element.render(self, file_out, cur_ind='') 
replaced by 
super().render(file_out, cur_ind='')
=> html_render.py, Element.render replaced by super().render

students/AndyKwok/lesson03/list_lab.py, students/AndyKwok/lesson03/mailroom.py
List_lab.py is ready for review. 
Mailroom.py requires additional testing to debug prior to submission.
=> list_lab.py ready for review

students/ShinTran/lesson01/break_me.py, students/ShinTran/lesson02/FizzBuzz.py, students/ShinTran/lesson02/PrintGrid.py, students/ShinTran/lesson02/Series.py
Lesson 1 and Lesson 2 assignments
=> Lesson 1 and Lesson 2 assignments

students/AurelPerianu/Lesson10/mailroom_fp.py
I understand @property decorators are not needed. I tried to run the file without them and I am getting errors, so I kept them there.
=> Chapter 10

students/rob_sanchez/Lesson 6/mailroom_pt4.py, students/rob_sanchez/Lesson 6/mailroom_test.py
Refactored some parts of Mailroom pt4 to ensure that all functionality could be tested. Also completed unit tests to ensure that each component from Malroom pt4 is working as expected.
=> Completed Lesson 6 Assignment. 

students/stefanjp1/lesson07/html_render.py
Not sure why HTML output is not expected because the test_html_output8.html file looks the same as the example in the prompt.  Can you please let me know what is not looking correct? Thanks!
=> fixed inheritance issues.  

students/toddschultz/session03/mailroom.py, students/toddschultz/session03/strformat_lab.py
I had some git issues part way through session03. WIth Natasha slack assistance I re-cloned, so I think I'm good. Let me know if something was messed up along the way. 
This is getting fun! That mailroom was much more involved than I initially thought it would be. 
Oh, hopefully I got my tab issues settled as well. 
ToddS
=> Session03 complete

students/AndyKwok/lesson03/list_lab.py, students/AndyKwok/lesson03/mailroom.py, students/AndyKwok/lesson04/trigrams.py
Mailroom.py is ready for review. Necessary comments will be updated on part 2 in Lesson 4 .
list lab updated per previous comment.
Both are submitted on the website.
Can you please review the trigrams.py exercise and provide guidance if I am understanding the prompt from the exercise correctly? My current understanding is to build a dictionary using a book then use the dictionary to build another story in iteration till no more match can be found.
=> mailroom.py submission, list_lab.py updated per comment

students/SLammertink/Lesson04/kata.py, students/SLammertink/Lesson05/except_exercise.py, students/SLammertink/Lesson05/except_test.py
Still working on the Kata exercise from lesson 04!!
=> Added the except_excercise and except_test Lesson 5

students/ShinTran/lesson03/SlicingLab.py, students/ShinTran/lesson03/list_lab.py, students/ShinTran/lesson03/mailroom.py, students/ShinTran/lesson03/strformat_lab.py
=> Assignments for lesson 03

students/ltrisolini/Lesson02/fizz.py, students/ltrisolini/Lesson02/print_grid.py, students/ltrisolini/Lesson02/series.py
Hello :)
you can find lesson 2 exercises on GitHub, thank you!
=> Lesson 2 Exercises

students/mxwllndrsn/ex_dir/ex_text.rst, students/mxwllndrsn/readme.rst
Initial pull request to verify proper setup. 
Thanks!
=> added readme file to student dir

students/ShinTran/lesson02/Series.py, students/ShinTran/lesson03/mailroom.py
Added the sum series function, added a main test section to test the functions
=> Series Assignment Update

students/tlugosan/lesson01/break_me.py, students/tlugosan/lesson01/warmup1_diff21.py, students/tlugosan/lesson01/warmup1_makes10.py, students/tlugosan/lesson01/warmup1_monkey_trouble.py, students/tlugosan/lesson01/warmup1_near_hundred.py, students/tlugosan/lesson01/warmup1_parrot_trouble.py, students/tlugosan/lesson01/warmup1_sleep_in.py, students/tlugosan/lesson01/warmup1_sum_double.py, students/tlugosan/lesson02/FizzBuzz.py, students/tlugosan/lesson02/grid1.py, students/tlugosan/lesson02/grid2.py, students/tlugosan/lesson02/grid3.py
This is a batch submission of the first lesson's exercises. Working in batches as I do my homework throughout the day and I don't have access to my personal computer.
=> break_me excercise and first 7 warmups1 excersises

students/mxwllndrsn/lesson01/break_me.py
I know this is not required, getting some practice in.
Any feedback appreciated.
Thank you!
=> committing 'break_me' exercise from lesson01

students/toddschultz/session02/FizzBuzz.py, students/toddschultz/session02/series.py, students/toddschultz/session04/dict_lab.py, students/toddschultz/session04/file_lab.py, students/toddschultz/session04/mailroom2.py
Two notes about mailroom2.py:
1. I still have a bug in Quit. If you launch it and quit right away it's fine. If you first create a report then quit, you have to quit twice for it to work. If you Send Thank You's or do more involved steps first quit functionality does a few other strange things. I'd love some feedback on this so I could fix it. As a QA Manager it's killin' me.   :-)
2. As instructed I used a Dictionary for the user options. I don't see the advantage over the way I did it previously. So far I'm not a big fan of dictionaries, but I will continue to bang on them until we become friends. 
Thanks!
ToddS
=> Done ... just one bug left

students/stefanjp1/lesson09/mailroom_class.py, students/stefanjp1/lesson09/test_mailroom_class.py
=> added lesson09 mailroom file

students/rgpag/lesson10/mailroom_fp.py, students/rgpag/lesson10/test_mailroom_fp.py
Please review mailroom_fp and test_mailroom_fp
=> lesson 10 for review

students/Mintae_K/lesson02/lesson02_fizz.py, students/Mintae_K/lesson02/lesson02_grid_print.py, students/Mintae_K/lesson02/series.py
This is submittal for print grid problem.
=> add simple file

students/mxwllndrsn/lesson02/fizz_buzz.py, students/mxwllndrsn/lesson02/grid_printer.py
Submitting a pull request per the assignment.
Thanks!
Max
=> Lesson02 Grid Printer Submission

students/tfbanks/Lesson03/List_Lab.py
Submitting List_Lab.py exercise
=> Submittal of Lesson 3 List_Lab Exercise

students/tlugosan/lesson02/FizzBuzz.py, students/tlugosan/lesson02/fibonacci.py, students/tlugosan/lesson02/fibonacci_and_friends.py, students/tlugosan/lesson02/grid3.py, students/tlugosan/lesson02/lucas_numbers.py, students/tlugosan/lesson02/series.py
fibonacci_and_friends,py file is a little bit an overdone of the series.py implementation. But I wanted to get as many tries at this implementation as I could.
=> Lesson02 homework and exercises submission files

students/mxwllndrsn/lesson02/series.py
Submitting 'series.py' to complete lesson02! Let me know if my unit tests satisfy your requirements. 
Thank you,
Max
=> lesson02 complete, submitting series.py

students/ShinTran/lesson03/list_lab.py, students/ShinTran/lesson04/dict_lab.py, students/ShinTran/lesson04/kata.py, students/ShinTran/lesson04/mailroom2.py
Lesson 04 Assignments.
Plus a minor modification for the lesson 03 lab
=> Lesson 04 Assignments

students/ptfbanks/Lesson03/series01.py
Previous submittal request failed.
=> Added series01 file for lesson3, assignment1

students/tlugosan/lesson03/list_lab.py, students/tlugosan/lesson03/slicing.py
Full implementation of all sub tasks. I still have to work on committing interim coding and not full solution.
=> Lesson03 slicing exercise

students/tfbanks/Lesson03/strformat_lab.py
submitting lesson 3 strformat_lab.py file
=> strformat_lab.py submittal

students/AndyKwok/lesson04/mailroom_part2.py, students/AndyKwok/lesson05/except_exercise.py, students/AndyKwok/lesson05/except_test.py
Non-mailroom exercise for Lesson 5 is already ready for review. 
Thank you. .
=> Lesson 04 Submission

students/smitco/lesson07/html_render.py, students/smitco/lesson07/run_html_render.py, students/smitco/lesson07/test_html_render.py
I've completed steps 8 plus successful tests.
I am struggling with the indents however. Only a few of the lines are indenting properly. What tips/suggestions should I review to improve the indentation feature of this code?
=> Lesson 07 Html Render

students/Wieslaw_Pucilowski/lesson09/mailroom5_OO.py, students/Wieslaw_Pucilowski/lesson09/test_mailroom5.py
class Donor and class DonorsCollection, menu is a part of DonorsCollection.
=> Lesson09 assignment - Object Oriented Mailroom

students/smitco/lesson08/circle.py, students/smitco/lesson08/test_circle.py
Completed circle class exercise and test file
=> Lesson 08 circle class and test file

students/Mintae_K/lesson03/Slicing_lab_exercise.py
Added first exercise: Slicing Lab Exercise
other exercises will be worked later date
=> lesson03 works

students/tfbanks/Lesson03/List_Lab.py, students/tfbanks/Lesson03/Mailroom_pt1.py
retry with the pull request after I noticed a conflict, last time as well as this time I see the "able to merge" comment so not sure where the conflict was.  I saw you had some comments and I didn't many any of the changes you mentioned; was going to look later, but I can't see any comments anymore.  are those still visible or only when the request is open? I wanted to review a few others as well.
=> retry pull request for Mailroom pt 1 file

students/ptfbanks/Lesson03/3-2_list_lab.py
'Eager to get on with the next exercises.
=> Submitting lesson 3, list lab exercise.

students/Wieslaw_Pucilowski/lesson09/mailroom5_OO.py
Code changed to match "separation of concern" requirement.
I works however I'm not sure method definition inside Main class. some (DonorsCollection) are @staticmethod, others are just methods defined inside class Main, others are Main @classmethods (based on methods defined inside the class)
=> mailroom5_OO.py refractored to fill separation of concerns requirement

students/mxwllndrsn/lesson04/dict_lab.py, students/mxwllndrsn/lesson04/file_lab.py, students/mxwllndrsn/lesson04/mailroom_mk2.py
Didn't see a reason to use dictionary for donor date structure, but worked very well for function dispatch.
=> Submitting Mailroom Pt. 2

students/tlugosan/lesson03/mailroom.py, students/tlugosan/lesson03/strformat_lab.py
How do I validate the input to make sure that it fits the requirement. In both cases i need the input() as a string but also as an int or float. 
line 20: if not choice_actions.isnumeric() or int(choice_actions) not in range(1, len(actions) + 1)
line 38: if type(donation_amount) is not float:
=> lesson003: mailroom exercise

students/Wieslaw_Pucilowski/lesson09/mailroom5_OO.py
@classmethods replaced by methods in the __main_, only @staticmethods in class Main
=> mailroom5_OO.py final shape

students/rfelts/lesson04/mailroom.py
Couldn't figure out how to use variables to represent dictionary keys in string format statements. For example: print(("{key:<{name_padding}}  ${value:>{donation_padding},.2f}") .format(**my_dict)).
=> Submitting assignment 4

students/smitco/lesson09/mailroomOO.py, students/smitco/lesson09/test_mailroomOO.py
Completed lesson 09 exercise to refactor mailroom file using OO programming methods and test appropriately
=> Lesson 09 object oriented mailroom and test

students/smitco/lesson09/mailroomOO.py, students/smitco/lesson09/test_mailroomOO.py
Reworked the OO mailroom assignment and associated test file
The suggestions section mentioned a few functionalities not previously used like searching for a donor or saving the updated list. Should those be added into this file, or do I just need to have the code structured to add those in the future?
=> Lesson 09 OO mailroom and test file reworked

students/tfbanks/Lesson03/Mailroom_pt1.py, students/tfbanks/Lesson03/strformat_lab.py, students/tfbanks/Lesson04/Mailroom_pt2.py, students/tfbanks/Lesson04/Trigrams.py
Dictionaries made this much easier, the only gI couldn't figure out was sorting the donors.  everything I read, researched didn't seem to work the way I set it up.  Other than that performs as expected.
=> submitting lesson04 mailroom_pt2

students/RoyC/Lesson02/draw_grid.py, students/RoyC/Lesson02/fizz_buzz.py, students/RoyC/Lesson02/series.py
This is my completed submittal for Lesson 2, Parts 1, 2 and 3.
=> Roy Crowley's Lesson 2 submittal

students/toddschultz/session05/mailroom3.py
I'm really starting to like try\except statements; cool stuff. 
When I tried the comprehension on line 117, I ran into 
https://stackoverflow.com/questions/16641119/why-does-append-return-none-in-this-code. I'm going to do some investigation on why appending was returning None, but it works with a print statement. Decided to add that to my list of things to investigate, but call it done and move on. Any hints or suggestions welcome.
=> Mailroom3.py

students/ShinTran/lesson04/kata.py, students/ShinTran/lesson04/mailroom2.py, students/ShinTran/lesson05/mailroom3.py
=> lesson 4 assignment updates

students/tfbanks/Lesson04/Trigrams.py
this one was a very interesting and tricky assignment.  I didn't use functions though as I built it step by step as you will see in the logic flow of the coding.
=> finished file

students/Mintae_K/lesson03/list_lab.py, students/Mintae_K/lesson03/strformat_lab.py
=> Lesson03 List Lab Exercise

students/smitco/lesson10/mailroomFP.py, students/smitco/lesson10/test_mailroomFP.py
Used map, filter and sum/reduce to add matching contribution function to the exercise
Based this assignment off mailroom4 file
=> Lesson 10 mailroom functional programming and test file

students/Wieslaw_Pucilowski/lesson10/mailroom5_FP.py
removing data input from DonorsCollection class
=> updated mailroom5_FP.py

students/ShinTran/lesson06/Args_kwargs_lab.py, students/ShinTran/lesson06/Test_args_kwargs_lab.py, students/ShinTran/lesson06/cigar_party.py, students/ShinTran/lesson06/mailroom4.py, students/ShinTran/lesson06/test_cigar_party.py, students/ShinTran/lesson06/test_mailroom4.py
=> Lesson 6 assignments

students/AndyKwok/lesson06/mailroom_part4.py, students/AndyKwok/lesson06/test_mailroom.py
Ready for submission, mailroom_part4.py was modified a little from previous lesson due to findings from test lessons and suggested improvements.
=> Submission

students/ltrisolini/Lesson03/list_lab.py, students/ltrisolini/Lesson03/slicing.py
Here is the first exercise for Lesson 3, thanks!
=> Lesson 3 first exercise

students/srepking/readme.rst
=> Lesson 1 Readme.rst

students/ptfbanks/Lesson03/pf_mailroom.py
I to admit, I needed to consult a variety of other students work to get started on this one.   It was revealing to see the variety of methods employed to meet the assigned specifications.  Much in the assignment required research well beyond the materials covered to date.
=> Submitting lesson3 mailroom exercise

students/ABartles/Exercise5/Mailroom.py, students/ABartles/Exercise5/except_exercise.py, students/ABartles/Exercise5/except_test.py
Please let me know if there are any questions/concerns. Attempted to fix pickups identified in mail room ex4. Thank you for your help.
=> Exercise 5 Ready for review.

students/tfbanks/Lesson05/Mailroom_pt3.py
=> Mailroom_pt3 submission

students/ShinTran/lesson06/TestMailRoom4.py, students/ShinTran/lesson06/mailroom4.py
=> Assignment 6 updates

students/srepking/Lesson2/FizzBuzz.py, students/srepking/Lesson2/Grid.py, students/srepking/lesson01/break_me.py
Hi, 
I added the Lesson 2 Grid Assignment for review. Please look at Grid.py
Thank you!
Shane
=> Shane Repking Added Lesson 2 Grid Assignment

students/tlugosan/lesson06/cigar_party.py, students/tlugosan/lesson06/mailroom4.py, students/tlugosan/lesson06/test_cigar_party.py, students/tlugosan/lesson06/test_mailroom4.py
IS it possible to test only in the intermediary tests like the following? And what would be the SOMETHING. I was thinking to try to read the input messages that are printed but I failed. Would that be a correct approach? 
def test_tanks_existing_donor(capsys):
test_input = ['1', 'list']
with mock.patch('builtins.input', side_effect=test_input):
mailroom.select_action_dictionary('1', mailroom.switch_func_dict)
captured = capsys.readouterr()
out = captured.out.strip()
err = captured.err.strip()
assert SOMETHING
=> Lesson06: cigar and mailroom unit_test files

students/srepking/Lesson2/FizzBuzz.py, students/srepking/Lesson2/series.py
Submittal for Lesson 2 -FizzBuzz and Lesson 2-Series.
Thank you!
Shane
=> Shane Repking Lesson2 Submittal FizzBuzz and Series

students/astrawmyer/lesson04/dict_lab.py, students/astrawmyer/lesson04/mailroom.py
I wasn't sure what was meant in the instructions to use a dict to write the letter. My code uses a function with a string and a flat input and I have no idea how i would modify that without making it complicated.
=> Lesson 4 Mailroom

students/ShinTran/lesson07/html_render.py, students/ShinTran/lesson07/run_html_render.py, students/ShinTran/lesson07/test_html_render.py
=> Lesson 7 Assignment

students/Craig_Morton/lesson02/Grid_Exercise.py, students/Craig_Morton/lesson03/list_lab.py, students/Craig_Morton/lesson03/mailroom.py, students/Craig_Morton/lesson03/slicing_lab.py, students/Craig_Morton/lesson03/strformat_lab.py
Lesson 3 assignment submission.
=> lesson 3 assignments

students/tfbanks/Lesson06/Mailroom_pt4.py, students/tfbanks/Lesson06/Test_Mailroom_pt4.py
I updated the mailroom test file based on your comments.
=> updates to lesson 6 mailroom tests

students/astrawmyer/lesson04/mailroom.py, students/astrawmyer/lesson04/trigram.py
Incorporated mailroom feedback. Completed Trigram.
=> Lesson 4 submission

students/ShinTran/lesson08/circle.py, students/ShinTran/lesson08/sparse_array.py, students/ShinTran/lesson08/test_circle.py
=> Lesson 8 Assignments

students/srepking/Lesson03/mailroom.py, students/srepking/Lesson04/activity2.py, students/srepking/Lesson04/dict_lab.py, students/srepking/Lesson04/kata.py, students/srepking/Lesson04/mailroom2.py
Hi, 
Please let me know if you want me to do more with the kata. I feel like I could really go down a rabbit hole working on punctuation and paragraphs and such.
Thanks!
=> Lesson04 Mailroom and Kata Ready for Review

students/srepking/Lesson04/mailroom2.py
I updated the file based on the previous pull comments. Thank you!
=> Updated file based on comments.

students/Craig_Morton/lesson05/exceptions.py, students/Craig_Morton/lesson05/mailroom_pt3.py
Lesson 5 assignments submission.
=> Lesson 5 assignments

students/ptfbanks/Lesson04/pf_mailroom-2.py
Submitting my solution for Lesson 4 mailroom 2.
FYI...  I in the exercise I attempted to create a subdirectory to the current directory at users request.  I could not get that to work and commented it out.  My attempts are reflected in the comment.
This was a challenging exercise, and frustrating, but I was pleased with being able to complete it.
=> Submitting coursework for Lesson 4 - mailroom 2

students/ShinTran/lesson09/oo_mailroom.py, students/ShinTran/lesson09/test_oo_mailroom.py
Lesson 9 assignment, incomplete, but for error checking.
=> Lesson 9 Assignment

students/tfbanks/Lesson07/html_render.py, students/tfbanks/Lesson07/run_html_render.py, students/tfbanks/Lesson07/test_html_render.py
Turning in the html assignment with the associated run and test files.
=> lesson 7 submittal

students/srepking/Lesson06/mailroom4.py, students/srepking/Lesson06/test_mailroom4.py
=> Lesson 6 Ready for Review

students/Chris_Hallen/lesson01/break_me.py, students/Chris_Hallen/lesson02/fizzBuzz.py, students/Chris_Hallen/lesson02/gridPrinterPart1.py, students/Chris_Hallen/lesson02/gridPrinterPart2.py, students/Chris_Hallen/lesson02/gridPrinterPart3.py, students/Chris_Hallen/lesson02/series.py, students/Chris_Hallen/lesson03/list_lab.py, students/Chris_Hallen/lesson03/mailroom.py, students/Chris_Hallen/lesson03/slicing.py, students/Chris_Hallen/lesson03/strformat_lab.py
I installed a linter in Atom - Flake8, cleaned up some of the little stuff - whitespace, added spaces, added comments,  etc - to programs I already commited.  I am also committing a couple of new programs I completed.  
My short term goal is to do more commits, more often.  I would like to do perhaps one commit a week rather than one a month.
=> Added a couple of programs, installed a linter -Flake8-and cleaned up previous commits

students/AndyKwok/lesson08/A_Circle.py, students/AndyKwok/lesson08/circle_test.py
Completing final touches for lesson 07.
Lesson 08 is ready for review.
Thanks.
=> Lesson 08 Submission

students/tfbanks/Lesson08/circle.py, students/tfbanks/Lesson08/test_circle.py
submitting lesson 8 circle.py and test_circle.py files
=> lesson 8 Submittal

students/AleGuardia/lesson2/FizzBuzz.py, students/AleGuardia/lesson2/print_grid.py, students/AleGuardia/lesson2/series.py
I built three functions with the different goals
=> Lesson 2 - Exercises

students/ShinTran/lesson10/fp_mailroom.py
=> Lesson 10 assignment

students/Craig_Morton/lesson06/mailroom4.py, students/Craig_Morton/lesson06/mailroom4_test.py, students/Craig_Morton/lesson06/template.txt
=> lesson 6 assignment submission

students/AndyKwok/lesson07/html_render.py, students/AndyKwok/lesson07/test_html_output.py
=> Lesson 07 submission

students/ltrisolini/Lesson04/mailroom2.py, students/ltrisolini/Lesson04/trigram.py
Lesson04 assignment1 mailroom part 2
=> mailroom part 2 with option to save emails in same directory

students/ptfbanks/Lesson05/except_test.py, students/ptfbanks/Lesson05/pf_except_exercise.py, students/ptfbanks/Lesson05/pf_mailroom-3.py
Exception exercise and Mailroom-3 submitted.
Two issues with mailroom acknowledged.
1) formatting in Write statements - I could not figure how to establish 2 decimal places.
2) Exception logic introduced a dual step to quit..  I could not figure how to prevent this
=> Submitting tasks 1 and 2 of lesson05

students/terrance_jones/README.rst, students/terrance_jones/lesson2/fizzbuzz.py, students/terrance_jones/lesson2/lesson2part1.py, students/terrance_jones/lesson2/lesson2part2.py, students/terrance_jones/lesson2/lesson2part3.py, students/terrance_jones/lesson2/series.py
finished lesson 2 assignments. please look grade each assignment
=> Lesson 2 assignments added 

students/terrance_jones/lesson2/fizzbuzz.py, students/terrance_jones/lesson2/print_grid.py, students/terrance_jones/lesson2/series.py
I have made the suggested corrections to the fizzbuzz.py and series.py assignments. I will use an IDE moving forward to prevent the indenting errors if that is okay
=> Corrections made to lesson 2 assignments

students/terrance_jones/lesson2/fizzbuzz.py, students/terrance_jones/lesson2/fizzbuzzUPDATED.py, students/terrance_jones/lesson2/series.py
please review fizzbuzzUPDATED and series.py. I think i have corrected the indentation errors, at least it seems that way on my end =).
=> please reveiw

students/Craig_Morton/lesson07/html_render.py, students/Craig_Morton/lesson07/html_render_test.py
=> Assignment 7 submission

students/tonylee/FizzBuzz.py, students/tonylee/SecondAssignment.py
Submit second assignment and FizzBuzz
=> Submit assignments

students/ltrisolini/Lesson05/mailroom3.py
=> Lesson5 mailroom3

students/terrance_jones/lesson2/fizzbuzzUPDATED.py
Please review fizzbuzzUPDATED.  i finally believe i corrected the indention errors. Thank you for your help.
=> adding correct fizzbuzz.py with indentions fixe

students/eldonab/lesson2/fizz_buzz.py
fizz_buzz exercise for review. Thank you!
=> adding my solution to Fizz_Buzz exercise for review.

students/Mintae_K/lesson04/dict_lab.py, students/Mintae_K/lesson04/mailroom2.py
=> mailroom dict

students/tonylee/FirstAssignment.py
Hi Professor,
I just delete a new line between 2 functions. Thanks.
=> adding firstAssignment.py

students/lauraannf/Lesson03/Slicing.py, students/lauraannf/Lesson03/list_lab.py, students/lauraannf/Lesson03/mailroom.py, students/lauraannf/Lesson03/strformat_lab.py
I've redone lesson 3 according to advice. No need to review, mostly for my own benefit.
=> Update for Lesson 03

students/ptfbanks/Lesson06/pf_mailroom4.py, students/ptfbanks/Lesson06/pf_mailroom_test.py
Test routines prepared.  Each of 5 ran, as far as I could tell, successfuly
=> Submitting refined mailroom and mailroom test files for lesson06

students/tonylee/FizzBuzz.py, students/tonylee/SecondAssignment.py, students/tonylee/Series.py, students/tonylee/mailroom.py, students/tonylee/mailroom2.py, students/tonylee/strformat_lab.py
Hi Professor,
I changed FizzBuzz with 3.6 version and follow Python convention. I also spent a quite amount of time for Series assignment, I hope you are happy with it. :-)
=> adding FizzBuzz and Series.py

students/srepking/Lesson09/donors.py, students/srepking/Lesson09/mailroom_9.py, students/srepking/Lesson09/test_mailroom_9.py
=> Lesson 9 Ready for Review

students/Craig_Morton/lesson09/mailroom_behavior.py, students/Craig_Morton/lesson09/mailroom_data.py, students/Craig_Morton/lesson09/mailroom_main.py, students/Craig_Morton/lesson09/mailroom_testing.py, students/Craig_Morton/lesson09/template.txt
lesson 9 assignment submission
=> lesson 9 assignment submission

students/mark_luckeroth/lesson01/break_me.py, students/mark_luckeroth/lesson02/FizzBuzz.py, students/mark_luckeroth/lesson02/Py210_lesson02_assignment_mjl.py, students/mark_luckeroth/lesson02/series.py
grid printer exercise submission.
=> added lesson02 assignment

students/Josh_HOff/gas/gasprices.py, students/Josh_HOff/lesson01/break_me.py, students/Josh_HOff/lesson02/FizzBuzz.py, students/Josh_HOff/lesson02/GridPrinter.py, students/Josh_HOff/lesson02/series.py
Parts 1, 2 and 3 complete. Do you have any tips to make part 3 a bit cleaner? I feel like I could reduce the number of lines or at least simplify it.
=> Josh Hoff Grid Printer Assignment

students/tonylee/Trigrams.py, students/tonylee/except_exercise.py, students/tonylee/except_test.py, students/tonylee/mailroom_part2.py, students/tonylee/mailroom_part3.py
Hi Professor, 
I am submitting these files for week 4 and week 5 exercises. 
Thanks Professor
=> adding exercises for week4 and week5

students/Craig_Morton/lesson10/mailroom_behavior.py, students/Craig_Morton/lesson10/mailroom_data.py, students/Craig_Morton/lesson10/mailroom_main.py, students/Craig_Morton/lesson10/mailroom_testing.py, students/Craig_Morton/lesson10/template.txt
=> Assignment 10 submission

students/Josh_HOff/lesson02/GridPrinter.py, students/Josh_HOff/lesson02/series.py
Completed the Series assignment. Successfully edited the sum_series function to work as a generalized function for lucas numbers and fibonacci series.
=> Josh Hoff Series Assignment

students/eldonab/lesson03/strformat_lab.py, students/eldonab/lesson2/grid_printer_combined.py, students/eldonab/lesson3/slicing_lab.py
I also combined the three parts of my solution to grid printer exercise into one file so I am adding it too.
=> adding solution to slicing lab exercises from lesson 3. 

students/ptfbanks/Lesson07/html_render.py, students/ptfbanks/Lesson07/run_html_render.py, students/ptfbanks/Lesson07/sample_html.html, students/ptfbanks/Lesson07/test_html_render.py, students/ptfbanks/Lesson08/pfcircle.py, students/ptfbanks/Lesson08/test_pfcircle.py
Materials represent a second effort.  I found this a more confusing exercise than instructive .  My response, having followed instructions appears much different from that of fellow students.  They have been able to greatly and neatly compress code.  I had hope to show work progression, but found myself conflicted between class specifications. I could not quite line up my indents correctly so my last sets of tests fail assertion tests.
=> submitted materials for Lesson 7

students/paul_jurek/lesson2/fizz_buzz.py, students/paul_jurek/lesson2/grid_printer.py
completed 'grid printer exercise' as part of lesson 2.  This includes all three functions.
=> Lesson 2: Grid Print Functions

students/Don_LaVallee/README.md, students/Don_LaVallee/lesson1/README.md, students/Don_LaVallee/lesson1/break_me.py, students/Don_LaVallee/lesson1/name_test.py
Learning how to use GIT process. It's different than SVN I've been using for JAVA coding.
=> Initial Lesson1 push

students/TressaHood/README.rst, students/TressaHood/lesson02/fizz_buzz.py, students/TressaHood/lesson02/grid_printer.py, students/TressaHood/lesson02/series.py, students/TressaHood/lesson03/list_lab.py, students/TressaHood/lesson03/mailroom.py, students/TressaHood/lesson03/slicing_lab.py, students/TressaHood/lesson03/strformat_lab.py
Added all the assignments for lesson 2.
=> This is the pull request for all of lesson 2

students/Josh_HOff/lesson03/list_lab.py, students/Josh_HOff/lesson03/slicing.py
Finished assert statements and used simplified code in all functions.
=> Completed Slicing Exercise in Lesson 3

students/paul_jurek/lesson2/series.py
Submitting Fibonacci series exercise
=> Lesson 2: Fibonacci Series

students/laura_denney/lesson03/coding_bat_logic1.py, students/laura_denney/lesson03/scratch.py, students/laura_denney/lesson03/slicing_lab.py
Added Slicing Lab Exercise Assignment to my repository for assignment submission. 
Assignment files:
slicing_lab.py
=> Lesson03 Pull Request

students/Mintae_K/lesson05/except_exercise.py, students/Mintae_K/lesson05/except_test.py, students/Mintae_K/lesson05/mailroom3.py
submitting lesson05 exception handling exercise
=> submitting lesson05 exception handling exercise

students/laura_denney/lesson03/list_lab.py, students/laura_denney/lesson03/strformat_lab.py
Submitting assignment List Lab.
=> Added list_lab.py to lesson03

students/tonylee/circle.py, students/tonylee/html_render.py, students/tonylee/mailroom_final.py, students/tonylee/mailroom_oo.py, students/tonylee/mailroom_part4.py, students/tonylee/run_html_render.py, students/tonylee/test_circle.py, students/tonylee/test_html_render.py, students/tonylee/test_mailroom_oo.py, students/tonylee/test_mailroom_part4.py
I am submitting all the python files
=> adding files

students/ABartles/Exercise8/Circle.py, students/ABartles/Exercise8/Test_Circle.py
Exercise 8 is ready for review. Please let me know if there are any issues or improvements needed.
=> Exercise8 For Review

students/ptfbanks/Lesson09/obj_mailroom.py, students/ptfbanks/Lesson09/test_obj_mailroom.py
Submitting materials for lesson 09.
=> Submitting materials for lesson09

students/srepking/Lesson10/donors_10.py, students/srepking/Lesson10/mailroom_10.py, students/srepking/Lesson10/test_mailroom_10.py
=> Lesson 10 ready for review.

students/paul_jurek/lesson03/list_lab.py, students/paul_jurek/lesson03/slicing_lab.py
submission of Lesson 3 slicing lab exercise.  As general question, do you care if we do in file testing with pytest rather than just the assert statements?
=> Lesson 3: Slicing Lab Exercise and List lab Exercise

students/eldonab/lesson03/mailroom.py, students/eldonab/lesson03/strformat_lab.py
Adding my solution to the assignment "Mailroom, Part 1".  Apologies for the delay. I've been traveling and didn't have a chance to study during the trip.
=> adding solution to mailroom part one from lesson 03

students/eldonab/lesson03/mailroom.py
Corrected indentation in "create_report" function and added docstrings to functions. Thank you for the feedback!
=> Made a couple of changes as per Natasha's feedback. 

students/AlyssaHong/Lesson02/FizzBuzz.py, students/AlyssaHong/lesson03/slicing.py
FizzBuzz.py
Changed function: while --> for in range()
=> changed function: while --> for in range()

students/KennanY/Lesson2/FizzBuzz.py
FizzBuzz project is ready for grading.
=> FizzBuzz project complete

students/Josh_HOff/lesson03/mailroom.py, students/Josh_HOff/lesson04/dict_lab.py, students/Josh_HOff/lesson04/file_lab.py, students/Josh_HOff/lesson04/mailroom2.py
Need to find out how to choose a directory to save the files to, and how to ask a user for a path to save the files to.
=> Mailroom2 Completed

students/laura_denney/lesson04/dict_lab.py, students/laura_denney/lesson04/mailroom.py, students/laura_denney/lesson04/path_file_lab.py
Submitting MailRoom Part 2 for assessment. 
Assignment file:
mailroom.py
=> Pull Request to submit Mailroom Part 2

students/ABartles/Exercise9/oo_mailroom.py
Good evening,
Please let me know if you have any questions or concerns. 
Thank you
=> Exercise9 for review

students/ltrisolini/Lesson10/mailroom_fc_2.py, students/ltrisolini/Lesson10/mailroom_fc_test.py
Lesson 10 assignments, thanks!
=> Lesson 10 assignments

students/paul_jurek/lesson03/mailroom.py, students/paul_jurek/lesson03/strformat_lab.py
completing lesson3.  Task 5 and 6 were a little unclear so I made some assumptions and generalized assignments a little.  Hope this is what was intended.
=> Submitting Lesson 3

students/ABartles/Exercise10/fp_mailroom.py
Please let me know if you have any questions or concerns.
Have a good evening,
Andrew
=> Exercise 10 for review

students/njschafi/Lesson2/FizzBuzz.py, students/njschafi/Lesson2/print_grid.py, students/njschafi/Lesson2/series.py
Added Lesson 2 assignment print_grid.py
=> Lesson 2 folder added print_grid.py Assignment

students/AlyssaHong/lesson03/list_lab.py, students/AlyssaHong/lesson03_1/slicing.py
updated Lesson3 Assignments:
Re-working the slicing assignment
List Lab Exercise
=> updated Lesson3 Assignment

students/Thai_H/lesson2/PrintGrid.py, students/Thai_H/lesson2/fizzbuzz.py, students/Thai_H/lesson2/series.py
the light at the end of the tunnel? :-)
=> generalized version of printgrid

students/laura_denney/lesson04/kata_fourteen.py
Pull Request to submit Kata Fourteen for assessment. 
Default source 'book' is sherlock_holmes.txt
HW File:
-kata_fourteen.py
=> Submitting Kata Fourteen for Assessment

students/terrance_jones/lesson5/mailroom_part3.py
Thank you for the awesome suggestion!  I think the new code reflects all of your suggested changes.
=> updated mailroom part 3 - please take a look when you have a moment

students/AlyssaHong/lesson03/list_lab.py, students/AlyssaHong/lesson03/strformat_lab.py
Submission of String Formatting Exercise in Lesson3
=> Submission of String Formatting Exercise in Lesson3

students/Thai_H/lesson2/fizzbuzz.py
worked on this fizzbuzz to get practice with github then will re-push series
=> fixed the order of the if/else to get correct fizzbuzz

students/AlyssaHong/lesson03/list_lab.py, students/AlyssaHong/lesson03/mailroom.py
=> added mailroom.py --part 1

students/patchcarrier/README.rst
Added README to students/patchcarrier directory
=> First Pull Request

students/TressaHood/lesson09/mailroom_base_functions.py, students/TressaHood/lesson09/mailroom_cl_inputs.py, students/TressaHood/lesson09/mailroom_donors.py, students/TressaHood/lesson09/test_mailroom_oo.py
added all of lesson 09, i got everything to work right through testing in the console, didn't time to finish my test_mailroom, unfortunately. But seems to work OK!
=> adding all of lesson 09

students/terrance_jones/lesson6/cigar_party.py, students/terrance_jones/lesson6/mailroom_part4.py, students/terrance_jones/lesson6/test_cigar_party.py, students/terrance_jones/lesson6/test_mailroom_part4.py
Please take a look at mailroom part 4 in lesson 6. Are there other parts of the code that you suggest I write a test for? As always, I welcome your feedback.
=> adding lesson 6 assignment

students/Josh_HOff/lesson05/except_exercise.py, students/Josh_HOff/lesson05/except_test.py
=> Finished Exceptions Exercise - Josh Hoff

students/laura_denney/lesson_05/except_exercise.py, students/laura_denney/lesson_05/except_test.py
finished work on except_exercise.py, submitting for assessment
=> Pull Request for Exceptions Exercise

students/eldonab/lesson04/kata.py, students/eldonab/lesson04/mailroom2.py, students/eldonab/lesson05/except_exercise.py, students/eldonab/lesson05/except_test.py, students/eldonab/lesson05/mailroom3.py
Adding solution to kata and part two of mailroom with updates.
=> Kata trigrams and updated mailroom, part two. 

students/Thai_H/lesson2/series.py, students/Thai_H/lesson3/slicing.py
I totally did not see the mentioning of assertion!
=> cleaned up extra blank lines and added assertion statements

students/MichaelM/lesson2/Lesson2_Ex1.py
testing GitHub, no review necessary...
=> lesson2, commit1, first stack of boxes

students/terrance_jones/lesson6/mailroom_part4.py, students/terrance_jones/lesson6/test_mailroom_part4.py
I added test for both the create report and letter portions of mailroom part 4. I had to make some slight changes to the mailroom file and the test mailroom file but I think It works. As always, I welcome your feedback and thank you for the encouragement.
=> updating lesson 6 assignments

students/laura_denney/lesson_05/mailroom_part3.py
Submitting Mailroom Part 3 for assessment 
HW File:
mailroom_part3.py
=> Submitting Mailroom Part 3 for Assessment

students/patchcarrier/Examples/scope.py, students/patchcarrier/Lesson02/fizzbuzz_exercise.py, students/patchcarrier/Lesson02/grid_printer_exercise.py, students/patchcarrier/Lesson02/series.py
Submitting my work for all three exercises in Lessson 02.
=> Lesson 02 Exercises

students/Dennis_Coffey/README.rst, students/Dennis_Coffey/lesson02/fizz_buzz.py, students/Dennis_Coffey/lesson02/grid_print.py, students/Dennis_Coffey/lesson02/series.py
Submitting lesson 2 assignments.  This includes the following files (all of lesson 2):
- fizz_buzz.py
- grid_print.py
- series.py
Also included in this pull is the README.pst file.  I thought I had done the pull correctly for this before but it seems like I didn't do it correctly.  I am new to git and apparently did something wrong on my initial attempt.  The git video lesson in lesson 2 helped me understand how to do the commits and pulls.
=> Lesson 2 Assignments

students/terrance_jones/lesson4/trigrams.py
hi, I looked at my progress and realized I didn't complete this problem. didn't want it to bring down my grade. honestly, it is a bit confusing for me.  now quite understanding the directions for the final piece I guess.
=> adding trigrams

students/eldonab/lesson04/mailroom2.py, students/eldonab/lesson05/mailroom3.py, students/eldonab/lesson06/mailroom4.py, students/eldonab/lesson06/test_mailroom4.py
in mailroom2:
-fixed indenation in letter_to_all()
-removed ":c/" from file path directory in letter_to_all()
in mailroom3:
-fixed indenation in letter_to_all()
-removed ":c/" from file path directory in letter_to_all()
-removed exit() in main function as it was unnecessary.
=> mailroom2, mailroom3

students/paul_jurek/lesson05/mailroom.py
This is resubmission of previously accepted lesson05 pull request #1121 which includes improvements to mailroom portion of lesson05 assignment.  Updates below.
* Updated try/except blocks based off comments
* added a list comprehension as requested in review
* improved code in few areas to make better user experience
=> Lesson05: Updated submission with improvements to Mailroom

lesson_2/fizzbuzz.py, lesson_2/grids.py, lesson_2/series.py
Still getting used to using git (that's why I'm submitting all the assignments at one.
On the Fibonacci part, I'm a little unsure what 'assert' is used for. I get that it can show you an error in your function, but it doesn't really seem that helpful, since I get an error anyway.
=> Homework lesson 2 assigments complete

students/Thai_H/lesson3/list_lab.py
=> Lesson 3 - list_lab.py

lesson02/fizz_buzz.py, lesson02/grid_patterns.py, lesson02/series.py
I also have a text file of testing of this grid pattern file. Unsure if it should be included in submission for reference. Left out for now.
=> Grid patterns file for lesson 2

students/Cracolici_Jon/lesson04/JonCracolici_Kata.py, students/Cracolici_Jon/lesson04/JonCracolici_L4_Mailroom2.py
Please take a look and let me know if you feel my programs are ready for grading.
=> Uploading work for lesson04

students/njschafi/Lesson03/Slicing.py, students/njschafi/Lesson03/list_lab.py, students/njschafi/Lesson03/mailroom.py, students/njschafi/Lesson03/strformat_lab.py
Added the following Lesson03 assignments for grading:
Slicing.py
list_lab.py
mailroom.py
strformat_lab.py
=> adding all of Lesson 3 assignments

students/Thai_H/lesson3/string_formattng.py
first iteration of the string formatting lab, pls review
=> string formatting review please

students/AlyssaHong/Lesson04/mailroom_part2.py, students/AlyssaHong/Lesson04/trigrams.py
added Lesson04 assignment: trigrams.py
=> added Lesson04 assignment: trigrams.py

students/jstrauss123/README.rst
added a readme file -- jstrauss123
=> added a readme file -- jstrauss123

students/laura_denney/lesson06/arg_kwarg_lab.py, students/laura_denney/lesson06/cigar_party.py, students/laura_denney/lesson06/mailroom_part4.py, students/laura_denney/lesson06/test_arg_kwarg_lab.py, students/laura_denney/lesson06/test_cigar_party.py, students/laura_denney/lesson06/test_mailroom_part4.py, students/laura_denney/lesson_05/mailroom_part3.py
Pull Request for submitting Mailroom Part 4 Assignment. 
I had a little bit of difficulty with this assignment, as most of my functions were not returning anything and so assert statements didn't work. I modified the functions to remedy this, making it more testable. 
Still not 100% confident on the testing process though in terms of real-life examples.
=> MailRoom Part 4 - Unit Testing

students/Cracolici_Jon/lesson05/JonCracolici_Mailroom3.py, students/Cracolici_Jon/lesson05/except_exercise.py, students/Cracolici_Jon/lesson05/except_test.py
I will be making the variables all snake case in lesson 6. I'm not sure how I got it in my head that functions are snake case and variables just lower. I will also be refactoring the user input checking to make it more testable. Thanks!
=> Lesson 5 work uploaded

students/avalvillar/lesson3/list_lab.py, students/avalvillar/lesson3/slicing_lab.py
First lab for lesson 3 complete.
=> Added the lesson 3 directory as well as the slicing lab file.

students/AlyssaHong/Lesson05/except_exercise.py, students/AlyssaHong/Lesson05/except_test.py, students/AlyssaHong/Lesson05/mailroom_part3.py
added Lesson05 assignment: Exception Exercise
=> added Lesson05 assignment: Exception Exercise

students/paul_jurek/lesson06/mailroom.py, students/paul_jurek/lesson06/test_mailroom.py
Submission of lesson06 exercise for mailroom testing.
=> Lesson06 - Mailroom Testing

students/njschafi/Lesson03/mailroom.py, students/njschafi/Lesson04/mailroom.py
Description of updates for each file below....
Mailrooom.py: 
- Now sorts report by total amount
- Cleaned up code to PEP8 standards
- Fixed other bugs (random printing, double names)
List_Lab.py:
- Fixed issue in series 1 that was printing 'p' instead of the fruit
- Wrote remaining code for series 3
=> Revisions to Lesson03 Assignments: List_Lab and Mailroom

students/Thai_H/lesson3/mail_room.py
=> mail_room.py submision

students/njschafi/Lesson03/mailroom.py, students/njschafi/Lesson04/mailroom.py, students/njschafi/Lesson04/trigrams.py, students/njschafi/Lesson05/except_exercise.py, students/njschafi/Lesson05/except_test.py, students/njschafi/Lesson05/mailroom.py
Adding the following Lesson04 assignments:
- Trigrams.py
Adding the following Lesson05 assignments:
- except_exercise.py 
- except_test.py (supporting file)
- mailroom.py 
Cleaned up the following files by removing unneeded function calls and cleaned up more per pep8.
- mailroom.py for lesson3/4
=> Adding assignments trigrams.py, except_test.py, mailroom.py plus other changes

students/cocokaku/lesson2/fizzbuzz.py, students/cocokaku/lesson2/series.py
added files fizzbuzz.py and series.py to lesson2 folder
=> completed lesson 2 exercises fizzbuzz and fibonacci series

students/jstrauss123/lesson02/fizzbuzz.py, students/jstrauss123/lesson02/print_grid_part2.py, students/jstrauss123/lesson02/print_grid_part3.py, students/jstrauss123/lesson02/series.py
Finished the print grid part 2 & 3 exercises
=> lesson02 - print grid part 2 & 3

lesson02/series.py, students/dominic_martin/README.rst, students/dominic_martin/lesson02/fizzBuzz.py, students/dominic_martin/lesson02/gridPrint.py
Hello, 
This PR is for the three Lesson 02 Assignments.  I apologize for the delay in submitting this - I had to resolve a few errors when committing files to git.  
V/R,
Dominic Martin
=> Lesson 02 Assignment Submissions

students/avalvillar/lesson3/mailroom.py
Completed file for mailroom in lesson 3.
=> Lesson 3 mailroom lab file added.

students/njschafi/Lesson06/mailroom.py, students/njschafi/Lesson06/test_mailroom.py
Refactored mailroom.py to allow easier testing. Also adding the test file test_mailroom.py to the repo.
=> Adding lesson06 assignments

students/john_rogers/lesson02/FizzBuzz.py, students/john_rogers/lesson02/coding_bat.py, students/john_rogers/lesson02/grids.py, students/john_rogers/lesson02/series.py
First exercise completed, grids.py.
=> Adding lesson02 grids.py & FizzBuzz.py for John Rogers

students/mattclau/lesson02/fizzbuzz.py, students/mattclau/lesson02/grid.py
Adding grid exercise for lesson 2.
=> Adding grid.py to lesson 2

students/Cracolici_Jon/lesson06/JonCracolici_Mailroom4.py, students/Cracolici_Jon/lesson06/test_JonCracolici_Mailroom4.py, students/Cracolici_Jon/lesson07/html_render.py, students/Cracolici_Jon/lesson07/run_html_render.py, students/Cracolici_Jon/lesson07/test_html_render.py, students/Cracolici_Jon/lesson08/Circle.py, students/Cracolici_Jon/lesson08/test_circle.py, students/Cracolici_Jon/lesson09/JonCracolici_OOMailroom.py
Adding Lessons 6 through 9. 9 is not quite done, but I wasn't sure if I have tomorrow to finish up or not, so I'm presenting what I have. Thanks!
=> adding lessons 6 though 9

students/jared_mulholland/lesson_4/mail_room.py, students/jared_mulholland/lesson_4/trigram.py
Added sherlock trigram to trigram file and updated mailroom script
=> Lesson 4 Homework

students/mattclau/lesson02/series.py
Finished a few days ago but didn't have a chance to push.
=> Adding series.py to lesson 2

students/terrance_jones/lesson7/html_render.py, students/terrance_jones/lesson7/run_html_render.py, students/terrance_jones/lesson7/test_html_render.py
I am submitting lesson 7 for grading. I know that is not totally accurate but honestly I have had an extremely difficult time with this assignment and just want to move on. Not sure if its the time of day that I work on my assignment and my mind just isn't clicking or if the assignment just doesn't seem interesting to me or what it is. The wording is kind of difficult to follow and while the tutorial was helpful, I feel like it was still missing several key pieces and wished it would've completely walked me through each step so I have a better understanding. I think that I have a good understanding of the core concepts in the lesson as I have been able to apply them to code that I have written outside of the assignments to make sure I understood the class concepts but this assignment was …
=> lesson 7 review

students/LouReis/README.rst
Completion of Initial Required Setup by doing first PR containing Readme file.
=> added a readme file, First Pull Request

students/KennanY/Lesson3/mailroom.py, students/KennanY/Lesson4/MailRoomPt2.py
Missing feature was added to the code.  Resubmitting the assignment
=> Mail room ver 2. - Missing feature added

students/Sahlberg/Lesson2/Assignment2_Functions.py
My first pull request...commence!
I have my three functions in the one python file.
=> Assignment 2 file added

students/njschafi/Lesson07/html_render.py, students/njschafi/Lesson07/run_html_render.py, students/njschafi/Lesson07/test_html_render.py
Submitting lesson 7 assignment, along with corresponding run and test files.
=> adding Lesson 7 assignment plus run file and test file

students/Dennis_Coffey/lesson06/mailroom.py, students/Dennis_Coffey/lesson06/test_mailroom.py
Added the following two files for submission:
- test_mailroom.py - Full suite of unit tests for mailroom.py
- mailroom.py - Updates to code to support performing unit tests
=> Lesson 06 submission

students/AleGuardia/Lesson05/mailroom_three.py
I had trouble finding were to use comprehensions but used in one function
=> Lesson 5 Mailroom with exception handling and comprehensions

students/avalvillar/lesson4/trigram_lab.py
*note: Is it possible to create paragraphs from the output join? (spent quite bit of time with no success)
=> Added trigram_lab file. 

students/jstrauss123/lesson03/mailroom.py
- removed else statement from main loop
- mail function updates:
- removed passing donor_list
- modified code to use and update donor_list directly
- modified code to prompt for name OR list existing
- various other cleanup and fixes
- print function updates:
- added / fixed code, print function now working properly, iterating through each donor to find required values
- added sort by largest donor contribution step
- unable to get sum function working, continues to error on : TypeError: 'float' object is not callable
was not able to resolve this so stuck with looping through contributions and adding to totamt
Example code:  sum(contrib_amts)
=> updated mailroom code - fully functioning

students/mattclau/lesson03/list_lab.py
Completed list_lab exercise.  I made copies of the list for each series because it didn't make sense to me to use the modified list from the previous series especially when doubling the list would create an untenable list for use when asking about fruit preferences.
=> Adding list_lab.py for lesson03

students/terrance_jones/lesson8/circle.py, students/terrance_jones/lesson8/test_circle.py
=> lesson 8 edits made

students/jeanruggiero/Lesson03/list_lab.py, students/jeanruggiero/Lesson03/slice_of_py.py
Ready to submit string slicing assignment.
=> Lesson03 Assignments

students/Sahlberg/Lesson3/Assignment3_StringSlicing.py
=> Assignment 3 Finished

students/AlyssaHong/Lesson06/mailroom_part4.py, students/AlyssaHong/Lesson06/test_mailroom_part4.py, students/AlyssaHong/Lesson07/html_render.py, students/AlyssaHong/Lesson07/run_html_render.py, students/AlyssaHong/Lesson07/test_html_render.py, students/AlyssaHong/Lesson08/circle.py, students/AlyssaHong/Lesson08/test_circle.py
added Lesson07/Lesson08 assignment
=> added Lesson07/Lesson08 assignment

students/LouReis/Lesson03/mailroom.py, students/LouReis/Lesson03/mailroom2.py, students/LouReis/Lesson04/mailroom2.py
Pull Request for mailroom.py exercise in Lesson03.
=> PR for mailroom.py exercise and mailroom2.py exercise

students/jared_mulholland/lesson_5/mail_room.py
Added improvements from Natasha's feedback
=> incorperated changes from feedback

students/njschafi/Lesson08/circle.py, students/njschafi/Lesson08/test_circle.py
Adding circle class assignment along with unit test file.
=> adding Lesson 8 assignment files

students/Sahlberg/Lesson2/Assign_2_fizz.py, students/Sahlberg/Lesson2/series.py
Finished the second two parts of the assignment.
=> Assignment 2 FizzBuzz and Fibonacci

students/LouReis/Lesson04/mailroom2.py
Natasha,
I made updates to mailroom2.py per your comments & recommendations.  Please review the newly updated file 'mailroom2.py' and let me know if I've missed any recommendations.
Lou
=> PR for mailroom2.py, Please review updates

students/dominic_martin/lesson03/Slicing.py, students/dominic_martin/lesson03/list_lab.py, students/dominic_martin/lesson03/mailroom.py, students/dominic_martin/lesson03/strformat.py
Hello, 
This is a PR for Lesson 03 assignments.
=> Added four assignments for Lesson03.

students/terrance_jones/lesson9/mailroom9.py, students/terrance_jones/lesson9/test_mailroom9.py
As always, I welcome your feedback. Thank you!
=> please review lesson 9

students/Thai_H/lesson6/mail_room_part4.py, students/Thai_H/lesson6/test_mail_room_part4.py
Refactored the summing each donor's donations, number of donation, and average. Also refactored inserting a donation into the dictionary of donors.
=> refractored mail room for test_mail_room

students/luyao_xu/lesson03/list_lab.py, students/luyao_xu/lesson03/slicing_lab.py, students/luyao_xu/lesson03/strformat_lab.py
slicing lab exercise finished from
=> add slicing lab exercise

students/Sahlberg/Lesson3/Assign3_ListLab.py, students/Sahlberg/Lesson3/strformat_lab.py
Finished 2 further sections of Assignment 3.
=> Assignment 3 List Lab and String Formats

students/Daniel_Spray/Lesson02/Grid_Printer.py, students/Daniel_Spray/Lesson02/fizz_buzz_test.py, students/Daniel_Spray/Lesson02/series.py
Made formatting changes to the Lesson02 assignments, and corrected the fizz_buzz_test to count 100 inclusive
=> Lesson02 pull request

students/jared_mulholland/lesson_7/html_render.py, students/jared_mulholland/lesson_7/run_html_render.py, students/jared_mulholland/lesson_7/test_html_render.py
This was a pretty tough assignment for me, and I think the wheels came off during the indent part. Any feedback would be very appreciated, especially with some of my render methods. I feel like I got a little confused as I created more and more subclasses (it looked like some of my stuff was very different from the code in the tutorial). Anyways, I need to move on to lesson 8. Thanks Jared
=> Lesson 7 homework

students/terrance_jones/lesson9/mailroom9.py
Hi Natasha,
Still not quite sure if I understand. I feel like I'm getting confused with the data collection class and it holding donor objects. specifically how I access the information for each object through the data collection class. in your example you used this at the end of the code:
donations = DonorCollection(Donor("natasha", [100]))
donations.add_donation("bob", [40])
How do I later access the donor information for "Natasha" if it was created through an instance of a donor collection but that is not a sub class of donor? not sure if i'm wording this right. Could you further expand on your previous comments?
Thanks!
=> adding updates to lesson9

students/LouReis/Lesson06/mailroom4.py, students/LouReis/Lesson06/test_mailroom4.py, students/LouReis/Lesson07/html_render.py, students/LouReis/Lesson07/run_html_render.py, students/LouReis/Lesson07/sample_html.html, students/LouReis/Lesson07/test_html_render.py
Hello,
This is a pull request to create the file to perform pytest.  Please review the following test file:
test_mailroom4.py
Per the assignment:  "it’s very hard to test the user interaction, but you can test everything else".  I avoided testing parts of the code involving user interaction.  I did make an attempt to test all of the code.
Thanks,
Lou
=> PR for Lesson06 test_mailroom4.py 

students/stefan_lund/Lesson_6/mailroom_6/mailroom_6_functions.py, students/stefan_lund/Lesson_6/mailroom_6/test_decimal_count.py
used try - except in mailroom_6_functions amount_input function and test_decimal_count
1. Looking at the enter_name function, name_input, amount_input and their support functions respectively, is this more in line of what you were looking for in this assignment?
2. When it comes to the other menu/main functions, they are essentially manipulating strings and I'm at a loss seeing how they can be structured to be test driven. A hint or example would be greatly appreciated.
3. In test_decimal_count I used assertRaises after except ValueError:, it works during testing but I'm unsure if it works as intended this way or if the assertRaises should be run only after try in a separate module for values throwing ValueError?
=> Understanding test based approach to writing the code

students/Sahlberg/Lesson3/mailroom.py, students/Sahlberg/Lesson4/mailroom2.py
=> Finished mailroom.py assignment.

students/Dennis_Coffey/lesson09/mailroomOO.py, students/Dennis_Coffey/lesson09/test_mailroomOO.py, students/Dennis_Coffey/lesson10/mailroom_fp.py, students/Dennis_Coffey/lesson10/test_mailroom_fp.py
Submittal for Lesson 09:
- mailroomOO.py
- test_mailroom.py
=> Lesson 09 - Object Oriented mailroom files

students/jvirtue/lesson02/fizzbuzz.py, students/jvirtue/lesson02/grid.py, students/jvirtue/lesson02/series.py
Grid printer exercise in Lesson 2.  Parts 1,2,3
=> grid assignment

students/terrance_jones/lesson9/mailroom9.py
please review lesson 9 mailroom9.py. any helpful suggestions you may have are welcomed. thank you
=> adding lesson 9 update

students/dominic_martin/lesson04/kata.py, students/dominic_martin/lesson04/mailroom.py
These two files are the assignment submissions for Lesson 04.
I apologize in advance for seemingly incomplete code.  I wrack my brain over simple tasks and fall behind quickly.  So I'd rather submit something and move along to the next Lesson than try to get something perfect.
=> Adding two new files: kata.py and mailroom.py for Lesson 04

students/LouReis/Lesson07/html_render.py, students/LouReis/Lesson07/run_html_render.py, students/LouReis/Lesson07/test_html_render.py, students/LouReis/Lesson08/circle_class.py, students/LouReis/Lesson08/test_circle_class.py, students/LouReis/Lesson09/mailroom5.py, students/LouReis/Lesson09/test_mailroom5.py
Please review the work for Lesson07:
run_html_render.py
test_html_render.py
html_render.py
sample_html.py
test_html_output1.py
There are 2 tests that are not working and I'm not sure why. I'm not sure how to complete the Part 5 items involving attributes, please provide an example.  I'm confused about what needs to be done, even after reviewing the tutorial.
Feedback: This doesn't seem like a useful exercise at this juncture, seems like an exercise of medium complexity involving OO, Classes, Subclasses would be much more appropriate and give the student the opportunity to master those topics without so much confusion, file parsing, etc. Progress in smaller iterations is more helpful then high complexity & confusion...
Lou
=> PR for Lesson 7 HTML Rendering

students/AlyssaHong/Lesson09/mailroom_part9.py
=> added Lesson09 assignment

students/terrance_jones/lesson10/mailroom_fp.py
Hi please review lesson 10. I started from a previous version of mailroom and not the most recent OO version. Any feedback you have is appreciated. Thanks!
=> please review lesson 10 

students/Sahlberg/Lesson4/Kata Fourteen Tom Swift Under Milk Wood/assignment4_kata.py, students/Sahlberg/Lesson5/except_exercise.py, students/Sahlberg/Lesson5/except_test.py, students/Sahlberg/Lesson5/mailroom3/mailroom3.py
try:
Exercise
except pull_request:
print('Thanks!')
=> Exceptions Exercise

students/luyao_xu/lesson04/dict_lab.py, students/luyao_xu/lesson04/file_lab.py, students/luyao_xu/lesson04/mailroom2.py, students/luyao_xu/lesson04/trigrams.py
Could you please also take a look at my homework 3 submission? I haven't received grades on the first 3 exercises of that homework. Thanks!
=> Lesson 4 lab exercise and hw

students/LouReis/Lesson010/mailroom_fp.py, students/LouReis/Lesson010/test_mailroom_fp.py, students/LouReis/Lesson09/mailroom5.py, students/LouReis/Lesson09/test_mailroom5.py
Hello Natasha,
Welcome back...
Please review the following files for Lesson09 & Lesson010:
Lesson09:
mailroom5.py
test_mailroom5.py
Lesson010:
mailroom_fp.py
test_mailroom_fp.py
Please provide detailed feedback and comments if you see anything I need to rework.  I'm not sure if Lesson09 mailroom5.py is designed just right in regards to the way I did the class.
Lou
=> PR for Lesson010 & Lesson09, mailroom5.py & mailroom_fp.py

students/avalvillar/lesson7/html_render.py, students/avalvillar/lesson7/test_html_render.py
Unable to get the indentation working - lots of trial and error.
=> Html render and test Html render files.

students/LouReis/Lesson09/mailroom_oo.py, students/LouReis/Lesson09/test_mailroom_oo.py
Hello Natasha,
I made some improvements but have a few issues with mailroom_oo.py:
-Attempt to use "find_donor" method but is says Donor doesn't have 'name' attribute (but it does)
-My get_report is not sorted, is there an easy way to do this with class objects?  I cannot use the sorted function as I did with dictionaries.
Thanks,
Lou
=> PR for Lesson09 Made some improvements to mailroom_oo

students/MzKhan/Readme.rst, students/MzKhan/Student Directory
Dear Instructor, 
Please check if I have submitted the Readme.rst file correctly via the GitHub. I look forward to your feedback. 
Thanks so much!
=> File Submission Via GitHub. 

students/LouReis/Lesson09/mailroom_oo.py
Hello Natasha,
I've updated the mailroom_oo.py program per your comments, getting closer.  Here's a few difficulties now:
-add_donor method fails and states it's missing 'name' but I am passing name, don't understand
-donations don't seem to be getting added to the DB as the get_report is not reflecting them
Please review & provide feedback
Lou
=> PR for Lesson09 mailroom_oo.py Made updates

students/alheadstrong/lesson_2/fizz_buzz.py, students/alheadstrong/lesson_2/grid_printer.py, students/alheadstrong/lesson_2/series.py
Hi there - adding the lesson 2 files for review. Note that for the grid printer, I added some optional parameters to use different characters or whole strings for the grid characters. If that was a function I wanted to use more, I would add some exception handling around the optional parameters or a function to convert arguments into strings to be used....but I left it as-is for now. 
Also, a question about documentation - I picked up a habit of comment blocks at the top of scripts with some file information. With git, I wonder if that's still appropriate - what do you think?
And last, I'm still getting the hang of "Pythonic" code, so would appreciate ways to simplify what I've got.
Thanks!
Alex
=> Lesson 2 files

students/dominic_martin/lesson05/except_exercise.py, students/dominic_martin/lesson05/mailroom3.py
Lesson 05 Assignment submissions.
=> Two new files for Lesson 05.

students/ethan_nguyen/lesson02/fizzbuzz.py, students/ethan_nguyen/lesson02/gridprint.py
=> Lesson 2 assignment

students/patchcarrier/Lesson09/ctor_test.py, students/patchcarrier/Lesson09/diamond.py, students/patchcarrier/Lesson09/diamond_super.py, students/patchcarrier/Lesson09/mailroom9.py, students/patchcarrier/Lesson09/super_test.py, students/patchcarrier/Lesson09/test_mailroom9.py
Submitting mailroom9.py code for the Lesson09 assignment.
=> Assignment09 Submission

students/LouReis/Lesson09/mailroom_oo.py
Hello Natasha,
I fixed the DonorDB class so that donations now get put into the DB, I also got the sort to work on the report.  
Please review and let me know if there's anything else that needs improving, any feedback is welcome...I want to make sure I'm addressing everything that needs addressing.
Lou
=> PR for Lesson09 Mailroom_oo.py

students/jared_mulholland/lesson_9/mail_room_class.py, students/jared_mulholland/lesson_9/test_mail_room_class.py
I am having some difficulties with testing for functions that have an input variable. I can't seem to get them to work correctly. See function send_thankyou(). Any help would be greatly appreciated.
Thanks, 
Jared
=> lesson 6 and lesson 9 homework

students/FlorentinPopescu/08_Mailroom_Part2_L4_FP.py, students/FlorentinPopescu/09_Kata_fourteen_L4_FP.py
Thank you for reviewing my solutions for Lesson 3. 
Please review the solutions for Lesson 4:
- 08_Mailroom_Part2_L4_FP.py
- 09_Kata_fourteen_L4_FP.py
Thank you.
=> Solutions_Assignments_Lesson4_FlorentinPopescu

students/njschafi/Lesson10/mailroom_fp.py, students/njschafi/Lesson10/test_mailroom_fp.py
Adding Lesson 10 Mailroom assignment
=> adding lesson 10 assignment

students/avalvillar/lesson8/circle.py, students/avalvillar/lesson8/test_circle.py
=> Circle class and accompying test class.

students/jvirtue/lesson03/list_lab.py, students/jvirtue/lesson03/strformat_lab.py, students/jvirtue/lesson03/string_seq.py
Final version for string_seq.  Work in progress for other assignments in lesson03
=> Submitted version of string_seq for lesson03

students/dominic_martin/lesson05/except_exercise.py, students/dominic_martin/lesson05/except_test.py, students/dominic_martin/lesson05/mailroom3.py, students/dominic_martin/lesson05/prompt_module.py
Hello, 
Mailroom3 has been updated since last commit.  
This commit also includes a prompt_module to import into mailroom3.py.
Also included is except_test module to import into except_exercise that was submitted the commit.
Last, I have verified again that I'm using 4 spaces.  I have switched the tabs to spaces feature in Sublime.  When selecting a line of code, I am showing four spaces per indent.
=> Adding three new files for Lesson05.

students/matt_casali/Lesson02/FizzBuzz.py, students/matt_casali/Lesson02/grid_printer.py, students/matt_casali/Lesson02/series.py
Finished exercises for Lesson 02. Please review. Thank you!
=> Adding files for Python210 Lesson02

students/jvirtue/lesson03/mailroom.py
Mailroom program for Lesson 3 Assignment #4 (Part I)
=> Final Copy of mailroom

students/alheadstrong/lesson_3/list_lab.py, students/alheadstrong/lesson_3/mailroom.py, students/alheadstrong/lesson_3/slicing_lab.py, students/alheadstrong/lesson_3/strformat_lab.py
I removed the change block header from the scripts this time. I also started "mailroom" with a 2d tuple, to try to avoid confusion with functions calling a list as a mutable sequence....but the mechanics of getting the new tuples to work seemed inelegant, more work than they were worth, so I switched to a 2d list instead.  Also ran each script with PyCharm to pick up PEP8 issues.
=> Lesson 3 Exercises

students/g_rama/fizzbuzz.py, students/g_rama/lesson02/series.py
Added series.py with fib, lucas and gen functions and fizzbuzz
=> Added series.py with fib, lucas and gen functions and fizzbuzz

students/jared_mulholland/lesson_10/mail_room_class_2.py, students/jared_mulholland/lesson_10/test_mail_room_class_2.py, students/jared_mulholland/lesson_6/mail_room_class_2.py, students/jared_mulholland/lesson_6/test_mail_room_class_2.py
Not sure why my last two tests of the projection method are not working with on the command line. They functions do work if I run them line by line.
=> added lesson 10 functions

students/FlorentinPopescu/10_Except_exercise_L5_FP.py, students/FlorentinPopescu/11_Mailroom_Part3_L5_FP.py
Thank you for reviewing my revised solutions for Lesson04.
Please review my solutions for assignments in Lesson05.
- 10_Except_exercise_L5_FP.py
- 11_Mailroom_Part3_L5_FP.py
Thank you.
=> Solutions_Assignments_Lesson05_FlorentinPopescu

students/luyao_xu/lesson05/except_exercise.py, students/luyao_xu/lesson05/except_test.py, students/luyao_xu/lesson05/mailroom3.py, students/luyao_xu/lesson06/mailroom4.py, students/luyao_xu/lesson06/test_mailroom4.py
=> Lesson 05 and lesson 06

students/Net_Michael/lesson6/mailroom4.py
given that the folder name containing the donations of each donor
=> submit - lesson6 mailroom5.py with edit to search accross any directory 

students/FlorentinPopescu/11_Mailroom_Part3_L5_FP.py
Thank you for reviewing my solutions for Lesson05.
Please review the revised solution for second assignment in Lesson05.
- 11_Mailroom_Part3_L5_FP
Thank you.
=> Revised_Solution_2nd_Assignment_Lesson05_FlorentinPopescu

students/ethan_nguyen/lesson03/list_lab.py, students/ethan_nguyen/lesson03/mailroom.py, students/ethan_nguyen/lesson03/slicing.py, students/ethan_nguyen/lesson03/strformat_lab.py
For the mailroom assignment, I created a class to represent a donor with its attributes, name, donated amount, number of donation and average per donation.  I then created a dictionary with key as the donor's name and value as a donor object.   I didn't see the tutorial on the mailroom assignment when I started the assignment but I could have created a list of donor with tuple.  Please let me know if my way is over complicated and more difficult to debug.
thanks,
=> Added assignments for lesson3

students/mattclau/lesson04/mailroom.py
In the end, I didn't use the dictionary for creating the letter as I wanted to have a flexible letter that would allow me to create a letter for everyone using a for loop or just for 1 letter when choosing option 1 to send a thank you.  Sending the whole dictionary didn't give me that flexibility.
=> Mailroom Lesson 4

students/matt_casali/Lesson03/list_lab.py, students/matt_casali/Lesson03/mailroom.py, students/matt_casali/Lesson03/slicing_lab.py, students/matt_casali/Lesson03/strformat_lab.py
Added files for Lesson03. Please review. Thank you!
=> Added files for Lesson03

students/ethan_nguyen/lesson03/mailroom.py
Please see the updated mailroom.py with changes in data structure and code styles.
thanks.
=> Update mailroom.py to use list and tuple

students/alheadstrong/lesson_4/mailroom_part2.py, students/alheadstrong/lesson_4/trigram.py
I've updated mailroom as mailroom_part2 with dictionaries, as well as fixing the report function to sort by total given, which was not included in previous version. I am passing the donor database as an unused argument into my "goodbye" function to keep it part of the dictionary - based user menu. Is that acceptable, or is there a better way to do it? 
For the trigram assignment, I used "Heart of Darkness" from Project Gutenberg, but didn't include that in the pull request - please let me know if you'd like to see that as well. 
Thanks,
Alex
=> Lesson 4 Pull Request

lesson01/break_me.py, students/christopher_gantt/README.rst
Readme File and my version of break_me.py
Thanks!
=> First Pull Request - Christopher Gantt

students/jvirtue/lesson03/mailroom.py
Updated notes in last pull request and updated code.
=> Revised mailroom.py per instruction comments

students/matt_casali/Lesson04/kata.py, students/matt_casali/Lesson04/mailroom_2.py
Added files for Lesson 04. Please review. Thanks Natasha!
=> Adding files for Lesson 04

students/g_rama/lesson04/mailroom_v2.py, students/g_rama/lesson04/trigram.py
1. Added the menu using dict as function
2. Updated to create the letters
=> lesson4 mailroom part 2 with dicts and trigram

students/scott_bromley/lesson02/fizz_buzz.py, students/scott_bromley/lesson02/grid_print.py
I added some "tests" of the different functions in main.  I'm open to suggestions as to how to make the functinos, especially print_grid_advanced, more "pythonic".
=> Added grid_print.py for lesson02 prid grid assignment

students/alheadstrong/lesson_5/except_exercise.py, students/alheadstrong/lesson_5/mailroom_part3.py
Hi - I wanted to check in regarding the exceptions exercise. The comments say to 'make lots of try/except blocks' but I'm getting what I think is the right output with only a couple. Am I missing something?
Thanks,
Alex
=> Lesson 5 Pull Request

students/ethan_nguyen/lesson04/mailroom2.py, students/ethan_nguyen/lesson04/trigram.py
Please see solutions for assignment 04, mailroom2 and trigram.
=> Added assignments for lesson04, mailroom2 and trigram

students/FlorentinPopescu/12_UnitTesting_of_MailroomPart4_L6_FP.py
Thank you for reviewing my revised solution for the second assignment of Lesson 5. 
Please review my solution for the assignment of Lesson 6.
- 12_UnitTesting_of_MailroomPart4_L6_FP.py
Thank you.
=> Solution_Assignment_Lesson06_FlorentinPopescu

students/matt_casali/Lesson05/except_exercise.py, students/matt_casali/Lesson05/except_test.py, students/matt_casali/Lesson05/mailroom_3.py
Added files for Lesson 05. Please review. Thank you!
=> added files for lesson 05

students/g_rama/lesson05/except_exercise.py, students/g_rama/lesson05/mailroom_v3.py
=> lesson 5 try catch

students/jvirtue/lesson04/mailroom_pt2.py, students/jvirtue/lesson04/triagram.py
Updated mailroom_pt2 with final version.  Submitted it to Self-learning site.
=> final version for mailroom

students/Gregg/lesson2/fizzbuzz.py, students/Gregg/lesson2/grid.py, students/Gregg/lesson2/series.py
Completed assignments for Lesson 2
grid.py
fizzbuzz.py
series.py
=> Gregg Heller: Lesson2

students/john_rogers/lesson09/donors.py, students/john_rogers/lesson09/mailroom.py
Incorporated feedback from Natasha into donors.py and mailroom.py for Lesson09.
=> Re-submitting Lesson09 for John Rogers.

students/FlorentinPopescu/13_Html_Render_L7_FP.py, students/FlorentinPopescu/14_Run_Html_Render_L7_FP.py, students/FlorentinPopescu/15_Test_Html_Render_L7_FP.py
Thank you for reviewing my solution for the assignment in Lesson 6. 
Please review my solution for the assignment in Lesson 7.
- 13_Html_Render_L7_FP.py
- 14_Run_Html_Render_L7_FP.py
- 15_Test_Html_Render_L7_FP.py
Thank you.
=> Solutions_Assignments_Lesson07_FlorentinPopescu

students/ethan_nguyen/lesson05/except_exercise.py, students/ethan_nguyen/lesson05/mailroom3.py
Please see exce3pt_exercise.py and mailroom03.py files for lesson05.   For mailroom03 exercise, I implemented the try catch logic to handle bad user's input for string name and numeric amount.  I can't find anywhere to implement the list comprehension.   I'm using dict to store donor's name and donation and I only print the key and values.
=> Added files for lesson05

students/matt_casali/Lesson06/mailroom_4.py, students/matt_casali/Lesson06/mailroom_testing.py
Added files for Lesson 06. For last function in mailroom_testing.py test, user will need to change file path to avoid a failure. This is a bit tedious, but I wanted to add this test despite the user interaction. Thanks!
=> Adding files for Lesson 06

students/scott_bromley/lesson03/list_lab.py, students/scott_bromley/lesson03/mailroom.py, students/scott_bromley/lesson03/slicing.py, students/scott_bromley/lesson03/strformat_lab.py
get_donor_summary feels to me a bit too "hacky"; I read in the directions we were to use only a data structure we've learned thus far so I used a list of lists
=> lesson03 exercises and assignment

students/FlorentinPopescu/16_Circle_class_L8_FP.py, students/FlorentinPopescu/17_Test_circle_class_L8_FP.py
Thank you for reviewing my solutions for the assignment in Lesson 7. 
Please review my solutions for the assignment in Lesson 8.
- 16_Circle_class_L8_FP.py
- 17_Test_circle_class_L8_FP.py
Thank you.
=> Solutions_Assignment_Lesson08_FlorentinPopescu

students/alheadstrong/lesson_6/mailroom_part4.py, students/alheadstrong/lesson_6/test_mailroom_part4.py
I used pytest exclusively, rather than unittest, and pulled my previous iteration of "mailroom" into many more small testable functions. 
I checked file writing content, but not any of the user input or the sys.exit. Let me know if you'd like to see either implemented and I'll give it a go!
=> Lesson 6 Pull Request

students/patchcarrier/Lesson10/mailroom10.py
Submitting work for assignment 10.
=> Adding mailroom10.py

students/jvirtue/lesson05/except_exercise.py, students/jvirtue/lesson05/except_test.py, students/jvirtue/lesson05/mailroom_pt3.py
Pull request for Lesson 05.  Submitted all assignments in one request to startlearning site.
=> Final published version for lesson05

students/Sahlberg/Lesson4/mailroom2.py, students/Sahlberg/Lesson5/mailroom3/mailroom3.py, students/Sahlberg/Lesson6/Mailroom3.py, students/Sahlberg/Lesson6/UnitTest.py, students/Sahlberg/Lesson6/archive/Mailroom3.py, students/Sahlberg/Lesson6/archive/UnitTest.py, students/Sahlberg/Lesson8/Circle.py, students/Sahlberg/Lesson8/circle_test.py
This request includes assignments 4-(mailroom 2 and kata), 5 -  mailroom3, 6 unittest, and Assignment 8.
Still working on 7.
=> Multi Assignment Request

students/jvirtue/lesson06/mailroom_ut.py, students/jvirtue/lesson06/test_mailroom_ut.py
Refactor code set to simplify it for unit testing.  Added a pytest test script for testing.  Please advise if my code is more pythonic in terms of readability.  I wanted to reduce the number of lines in my python script so consolidated multiple print lines into one.  I think it is more personal preference but curious.  This is ready for grading and submitted it to the class site.
=> Final submission for Unit tests with pytest

students/g_rama/lesson06/mailroom_v4.py, students/g_rama/lesson06/test_mailroom_v4.py
test_mailroom_v4.py::test_thank_you_letter_positive[dan-50-Thank you dan for donating 50 dollars generously.] PASSED                                                                   [ 10%]
test_mailroom_v4.py::test_thank_you_letter_positive[jeff-60-Thank you jeff for donating 60 dollars generously.] PASSED                                                                 [ 20%]
test_mailroom_v4.py::test_thank_you_letter_negitive[dan-50-Thank you sam for donating 50 dollars generously.] PASSED                                                                   [ 30%]
test_mailroom_v4.py::test_thank_you_letter_negitive[jeff-60-Thank you  for donating 60 dollars generously.] PASSED                                                                     [ 40%]
test_mailroom_v4.py::test_donor_details …
=> lesson 06 mock tests

students/mattclau/lesson07/html_render.py, students/mattclau/lesson07/run_html_render.py, students/mattclau/lesson07/test_html_render.py, students/mattclau/lesson08/circle.py, students/mattclau/lesson08/test_circle.py
I really struggled with this one because I've never gotten OO programming before in any of my classes. I  had to lean heavily on the tutorial at first, but by step 4, I was getting the hang of it and didn't need refer back to it.  I can't figure out why the test file keeps telling me that html_render doesn't take 3 arguments.
=> Lesson 7 html_render

students/matt_casali/Lesson07/html_render.py, students/matt_casali/Lesson07/run_html_render.py, students/matt_casali/Lesson07/test_html_render.py
Added files for Lesson 07. Please review. Thanks!
=> Added files for Lesson 07

students/MzKhan/lesson03/list_lab.py, students/MzKhan/lesson03/mailroom.py, students/MzKhan/lesson03/slice_sequences.py, students/MzKhan/lesson03/strformat_lab.py
Dear instructor, 
Please review my assignment 03. Please let me know if there is anything you'd like me to change to improve my skills. 
Thanks so much.
=> Assignment 03 Submission for the review. 

students/john_rogers/lesson10/donors_fp.py
Corrected donors_fp.py per feedback from Natasha.
=> Lesson10 final.

students/ethan_nguyen/lesson07/html_render.py, students/ethan_nguyen/lesson07/run_html_render.py, students/ethan_nguyen/lesson07/test_html_render.py
Please see attached html_render.py and pytest in test_html_render.py
=> Added homework 7

students/jvirtue/lesson07/html_render.py, students/jvirtue/lesson07/run_html_render.py, students/jvirtue/lesson07/test_html_render.py
I'm submitting final pull request for Lesson 07.
=> Lesson 07 Final assignment

students/MzKhan/lesson03/mailroom.py, students/MzKhan/lesson04/dict_lab.py, students/MzKhan/lesson04/file_lab.py, students/MzKhan/lesson04/mailroom2.py, students/MzKhan/lesson04/trigram.py
mailroom2.py
1) I create a folder "Letters" in the lesson04 directory to place all the letters to the donors.
2) I made improvements based on the previous feedback in regard to better coding practices. 
trigram.py
I'm a bit confused on the trigram algorithm. Please check my algorithm. 
I write out the text in multiple lines rather than one long line in the text format. 
I was not able to find if python has a method that writes line by line.
=> Assignment04

students/FlorentinPopescu/18_Object_Oriented_Mailroom_L9_FP.py, students/FlorentinPopescu/19_UnitTesting_of_ObjectOrientedMailroom_L9_FP.py
Thank you for reviewing my solution for the assignment in lesson 8.
Please review my solution for the assignment in lesson 9.
- 18_Object_Oriented_Mailroom_L9_FP.py
- 19_UnitTesting_of_ObjectOrientedMailroom_L9_FP.py
Thank you.
=> Solution_Assignment_Lesson09_FlorentinPopescu

students/matt_casali/Lesson08/circle.py, students/matt_casali/Lesson08/test_circle.py
Added files for Lesson 08. Please review. Thank you!
=> Added files for Lesson 08

students/jvirtue/lesson08/circle.py, students/jvirtue/lesson08/test_circle.py
=> final submission for lesson 08

students/mattclau/lesson10/cli_main.py, students/mattclau/lesson10/donor_models.py, students/mattclau/lesson10/mailroom_fn.py, students/mattclau/lesson10/test_donor_models.py
I used the mailroom OO version from the last lesson and adding the functional pieces requested for map/filter/reduce (sum).  I also made the changes to errors pointed out from the lesson 9 pull.
=> Adding files for lesson10

students/matt_casali/Lesson09/mailroom_9.py
Added file for Lesson 09. Please review. Thanks!
=> Adding files for Lesson 09

students/MzKhan/lesson05/except_exercise.py, students/MzKhan/lesson05/except_test.py, students/MzKhan/lesson05/mailroom3.py
Dear Reviewer, 
I've done the following. 
mailroom3.py - 
- Used the dict comprehension to create the dictionary.
- Used list comprehension
- Added exceptions - raised exception in the name_prompt() method. I catch that exception in the main method. 
- The code works. 
exception_exercise.py
added the exceptions and I got the good results. 
Please let me know if there is anything I should improve. 
Thanks so much for your feedback :)
=> Assignment05 Submission

students/matt_casali/Lesson09/mailroom_9_V2.py
Submitted a new version of the mailroom script. Please review. Thanks for the help!
=> Updating lesson09 mailroom script

students/MzKhan/lesson06/mailroom4.py, students/MzKhan/lesson06/test_mailroom4.py
Dear Instructor(s), 
I refactored some of the code in the mailroom3.py to do the unit testing. The mailroom4.py is the newest file with the refactored code as well as some style improvements.
test_mailroom4.py file contains the unit tests for the most of my code EXCEPT user inputs. In most cases I tested the individual methods that are called by a main method. The unit testing was an excellent exercise. 
Please provide me feedbacks to improve my skills. 
Thanks.
=> Assignment 06

students/FlorentinPopescu/20_Functional_Mailroom_L10_FP.py
Thank you for reviewing my solution for the assignment in lesson 9.
Please review my solution for the assignment in lesson 10.
- 20_Functional_Mailroom_L10_FP.py
Thank you.
=> Solution_Assignment_Lesson10_FlorentinPopescu

students/g_rama/lesson09/Donor.py, students/g_rama/lesson09/mailroom_oob.py, students/g_rama/lesson10/CLI.py, students/g_rama/lesson10/Donor.py, students/g_rama/lesson10/DonorCollection.py, students/g_rama/lesson10/mailroom_fp.py
=> Added the challenge factor with map function

students/matt_casali/Lesson10/mailroom_fp.py
Added file for Lesson 10. Please review. Thank you!
=> Added file for Lesson10

students/g_rama/lesson09/Donor.py, students/g_rama/lesson09/mailroom_oob.py
Reworked lesson 9 to make Donor class more of an Object
=> Reworked to make Donor class more object oriented

students/luyao_xu/lesson07/html_render.py, students/luyao_xu/lesson07/run_html_render.py, students/luyao_xu/lesson07/test_html_render.py
Here is the homework for lesson 07
=> Lesson 07 homework

students/MzKhan/lesson07/html_render.py, students/MzKhan/lesson07/run_html_render.py, students/MzKhan/lesson07/test_html_render.py
Dear instructor(s), 
Please check my work for Assignment 07. Please let me know if there is anything I can do to improve the code in the html_render.py file. 
Thanks.
=> Assignment 07

students/Gregg/lesson3/list_lab.py, students/Gregg/lesson3/mailroom.py, students/Gregg/lesson3/slicing.py, students/Gregg/lesson3/strformat_lab.py
Sorry if the commits look weird, my branch got off from the upstream (wouldn't let me pull upstream) and I wanted to back up by assignment files before trying to reset it. Instead of copying them I accidentally moved them so they might disappear for a commit.
=> Gregg Hele Lesson 3 assignments

students/ethan_nguyen/lesson09/cli_main.py, students/ethan_nguyen/lesson09/mailroom9.py, students/ethan_nguyen/lesson09/test_mailroom_oo.py
Please see the files for HW 9.  Mailroom with OO concepts
thanks,
=> Mail room OO

students/MzKhan/lesson08/circle.py, students/MzKhan/lesson08/test_circle.py
Dear Instructor(s), 
I think I am very confident about the concepts covered in assignment 8. I do have one question. 
To make 2*c1 (where c1=Circle(10)) to work, I used the magic method __rmul__(self, num). When this magic function is not available, the multiplication doesn't work for 2*c1. 
I implemented augmented addition and multiplication for the optional part of the assignment. I noticed during testing that my code works fine for the augmented assignments whether I implement the augmented addition, multiplication or not. 
Please provide me some description of implementing the augmented assignments. 
Thanks for your help.
=> Assignment08

students/Gregg/lesson3/mailroom.py, students/Gregg/lesson4/dict_lab.py, students/Gregg/lesson4/mailroom.py
I have tried to address most of your comments in my mailroom code - 
- Tried to use tuples and lists instead of dicts
- Eliminated global flag (that wasn't being used and was also needlessly a list)
- changed functions to string constants
- added sorting feature to report
But I do have a few questions - 
1. Some of your suggestions were focused on functions that returned values that were never used - some of these I had included because of suggestions here, as linked from the course material. (https://jeffknupp.com/blog/2018/10/11/write-better-python-functions/) - He suggests that all functions should return something even if its just for testability purposes. Have I gone too far and these functions are just too trivial to return a plain True, or whatever upstream output I ended up …
=> Lesson3 revisions

students/alheadstrong/lesson_10/mailroom_fp.py
Started from object oriented mailroom, pulled all remaining UI out of classes and added mapping, filtering and summing.
=> Lesson 10 

students/Ramkumar_Rajanbabu/Lesson03/Slicing_Lab.py
Still working on the list lab and string formatting assignment. Finished slicing lab.
=> Finished slicing lab

students/Ramkumar_Rajanbabu/Lesson03/List_Lab.py, students/Ramkumar_Rajanbabu/Lesson03/Slicing_Lab.py, students/Ramkumar_Rajanbabu/Lesson03/String_Formatting_Lab.py
Only fixed slicing lab, still working on other 2 exercises.
=> Fixed exchange_first_last, only used slicing for the function.

students/MzKhan/lesson10/mailroom/mailroom.py, students/MzKhan/lesson10/mailroom/test_mailroom.py, students/MzKhan/lesson10/mailroom_fp/cli_main_fp.py, students/MzKhan/lesson10/mailroom_fp/mailroom_fp.py, students/MzKhan/lesson10/mailroom_fp/test_mailroom_fp.py, students/MzKhan/lesson10/mailroom_oo/cli_main_oo.py, students/MzKhan/lesson10/mailroom_oo/mailroom_oo.py
Dear Natasha, 
I implemented map, filter and lambda functions in mailroom_fp project. I've added a method in the DonorCollection class called "projected_amount" instead of method name "challenge" in the instructions. I felt projected_amount was a better naming convention. I can correct that if you'd like. 
Please review my assignment and provide your feedback if I should improve the fp part of the assignment. 
Thanks so much for your help throughout the course. I look forward to taking the second python class towards the certificate. 
Muhammad
=> Assignment10

students/Ramkumar_Rajanbabu/Lesson03/mailroom_p1.py
Added sort feature and sorted by total_given. Fixed create a report function by adding a summary list to append donor name, total_given, num_gifts and avg_gift.
=> Finished mailroom p1
